ip_method: 0
manual_ip: 192.168.1.2
dns: 8.8.8.8
gateway: 192.168.1.1
subnet: 255.255.255.0
joint_characteristics:
- {effort_correction: 1.50053251, friction_transition_velocity: 0, friction_constant_term: -0.00999999978,
  friction_coulomb_coef: 0.239102736, friction_viscous_coef: 0.25152266, continuity_factor: 10}
- {effort_correction: 1.29893363, friction_transition_velocity: 0, friction_constant_term: 0.25,
  friction_coulomb_coef: 0.123982079, friction_viscous_coef: -0.0047618039, continuity_factor: 10}
- {effort_correction: 1.32860816, friction_transition_velocity: 0, friction_constant_term: 0.219999999,
  friction_coulomb_coef: 0.115950696, friction_viscous_coef: -0.173854992, continuity_factor: 10}
- {effort_correction: 1.2467382, friction_transition_velocity: 0, friction_constant_term: -0.0700000003,
  friction_coulomb_coef: 0.0233809967, friction_viscous_coef: 0.0246397872, continuity_factor: 10}
- {effort_correction: 1.1713295, friction_transition_velocity: 0, friction_constant_term: -0.00999999978,
  friction_coulomb_coef: 0.0117641361, friction_viscous_coef: 0.0274016745, continuity_factor: 10}
- {effort_correction: 1.20000005, friction_transition_velocity: 0, friction_constant_term: -0.00999999978,
  friction_coulomb_coef: 0, friction_viscous_coef: 0.0166083109, continuity_factor: 10}
- {effort_correction: 1.20000005, friction_transition_velocity: 0, friction_constant_term: 11.5699997,
  friction_coulomb_coef: 0, friction_viscous_coef: 63.8767738, continuity_factor: 10}
gripper_force_limit_scaling_factor: 0.1
