ip_method: 0
manual_ip: 192.168.1.3
dns: 8.8.8.8
gateway: 192.168.1.1
subnet: 255.255.255.0
joint_characteristics:
- {effort_correction: 1.48065436, friction_transition_velocity: 0, friction_constant_term: 0.0199999996,
  friction_coulomb_coef: 0.268388093, friction_viscous_coef: 0.309239119, continuity_factor: 2}
- {effort_correction: 1.28734756, friction_transition_velocity: 0, friction_constant_term: 0.239999995,
  friction_coulomb_coef: 0.151887119, friction_viscous_coef: 0.0599790961, continuity_factor: 2}
- {effort_correction: 1.30860281, friction_transition_velocity: 0, friction_constant_term: 0.310000002,
  friction_coulomb_coef: 0.119617626, friction_viscous_coef: -0.187822342, continuity_factor: 2}
- {effort_correction: 1.28547764, friction_transition_velocity: 0, friction_constant_term: -0.0399999991,
  friction_coulomb_coef: 0.0179036148, friction_viscous_coef: 0.0213090871, continuity_factor: 2}
- {effort_correction: 1.1643312, friction_transition_velocity: 0, friction_constant_term: 0,
  friction_coulomb_coef: 0.0526146404, friction_viscous_coef: 0.030950794, continuity_factor: 2}
- {effort_correction: 1.20000005, friction_transition_velocity: 0, friction_constant_term: 0.0199999996,
  friction_coulomb_coef: 0, friction_viscous_coef: 0.0213963352, continuity_factor: 2}
- {effort_correction: 1.20000005, friction_transition_velocity: 0, friction_constant_term: 7.32999992,
  friction_coulomb_coef: 0, friction_viscous_coef: 118.874084, continuity_factor: 2}
gripper_force_limit_scaling_factor: 0.1
