"""Generate a Bash completion script from the canonical registry and arguments."""
from __future__ import annotations

import shlex
from collections import defaultdict

from tatbot_cli import nodes
from tatbot_cli.registry import all_verbs

GLOBALS = ("--json", "--dry-run", "--explain", "--on", "--ee-tool", "--no-hop", "--help", "--version", "-q", "-v")


def bash(repo):
    children = defaultdict(list)
    flags = {"": list(GLOBALS)}
    arity = {"|" + flag: "1" if flag in ("--on", "--ee-tool") else "0" for flag in GLOBALS}
    choices = {"|--on": list(nodes.load(repo))}
    deprecated = {}
    for v in all_verbs():
        parts = v.name.split()
        for i, part in enumerate(parts):
            parent = " ".join(parts[:i])
            if part not in children[parent]:
                children[parent].append(part)
        flags[v.name] = []
        deprecated[v.name] = set()
        for arg in v.argument_spec.schema():
            deprecated[v.name].update(arg["deprecated_options"])
            for flag in arg["option_strings"]:
                if flag in arg["deprecated_options"]:
                    continue
                flags[v.name].append(flag)
                key = v.name + "|" + flag
                nargs = arg["nargs"]
                if nargs is None:
                    nargs = 0 if arg["action"] in ("store_true", "store_false", "count", "store_const") else 1
                arity[key] = str(nargs)
                if arg["choices"] is not None:
                    choices[key] = list(map(str, arg["choices"]))
    for name in flags:
        if name:
            flags[name] = list(dict.fromkeys([*flags[name], *(flag for flag in GLOBALS if flag not in deprecated[name])]))

    def array(name, mapping):
        # A sentinel represents the empty command path: associative Bash keys
        # cannot be empty. Every value is quoted data, never shell source.
        lines = [f"  local -A {name}=("]
        for key, value in mapping.items():
            data = "\n".join(value) if isinstance(value, list) else value
            lines.append(f"    [{shlex.quote(key or '_root_')}]={shlex.quote(data)}")
        return "\n".join([*lines, "  )"])

    return "\n".join([
        "# Generated by tatbot completion bash. Source explicitly; no startup file is edited.",
        "# Bash 4+; completion uses only shell builtins and filename lookup.",
        "_tatbot_complete() {",
        array("children", children), array("flags", flags), array("arity", arity), array("choices", choices),
        r'''  local path='' token flag key next word cur="${COMP_WORDS[COMP_CWORD]}"
  local pending=0 pending_key='' i tail=0
  COMPREPLY=()
  for ((i=1; i<COMP_CWORD; i++)); do
    token="${COMP_WORDS[i]}"
    if [[ "$token" == -- ]]; then tail=1; break; fi
    if [[ "$pending" != 0 ]]; then
      if [[ "$pending" =~ ^[0-9]+$ ]]; then
        pending=$((pending-1)); continue
      elif [[ "$token" != -* ]]; then
        [[ "$pending" == '?' ]] && pending=0
        continue
      else
        pending=0
      fi
    fi
    if [[ "$token" == -* ]]; then
      flag="${token%%=*}"; key="$path|$flag"
      [[ ${arity[$key]+present} ]] || key="|$flag"
      if [[ ${arity[$key]+present} && "$token" != *=* ]]; then
        pending="${arity[$key]}"; pending_key="$key"
      fi
      continue
    fi
    next="${children[${path:-_root_}]-}"
    while IFS= read -r word; do
      if [[ -n "$word" && "$word" == "$token" ]]; then
        path="${path:+$path }$word"; break
      fi
    done <<< "$next"
  done
  next=''
  local prefix=''
  if (( ! tail )); then
    if [[ "$cur" == --*=* ]]; then
      flag="${cur%%=*}"; key="$path|$flag"
      [[ ${arity[$key]+present} ]] || key="|$flag"
      next="${choices[$key]-}"
      prefix="$flag="; cur="${cur#*=}"
    elif [[ "$pending" != 0 ]]; then
      next="${choices[$pending_key]-}"
    elif [[ "$cur" == -* ]]; then
      next="${flags[${path:-_root_}]-}"
      [[ -n "$next" ]] || next="${flags[_root_]}"
    else
      next="${children[${path:-_root_}]-}"
    fi
  fi
  if [[ -n "$next" ]]; then
    while IFS= read -r word; do
      [[ -n "$word" && "$word" == "$cur"* ]] && COMPREPLY+=("$prefix$word")
    done <<< "$next"
  else
    while IFS= read -r word; do COMPREPLY+=("$prefix$word"); done < <(compgen -f -- "$cur")
    compopt -o filenames 2>/dev/null || true
  fi
}
complete -F _tatbot_complete tatbot
''',
    ])
