"""`tatbot schema` — the internal JSON tree and public Markdown reference."""

from __future__ import annotations

import json
import re
from pathlib import Path

from tatbot_cli import EXIT_NAMES, __version__, nodes
from tatbot_cli.registry import NOUN_SUMMARY, TIER_GATES, TIER_MEANING, TIERS, all_verbs, nouns


def _private_node_re() -> re.Pattern:
    """Node names to redact from public Markdown, from config/nodes.json —
    the deployment's own config, so no fleet hostname is frozen into source.
    Matches nothing when no fleet is described."""
    from tatbot_cli.registry import repo_root

    names = sorted(nodes.load(repo_root()), key=len, reverse=True)
    if not names:
        return re.compile(r"(?!x)x")  # matches nothing
    alt = "|".join(re.escape(n) for n in names)
    return re.compile(rf"(?i)(?<![a-z0-9])({alt})(?![a-z0-9])")


_PRIVATE_NODE = _private_node_re()

# The JSON schema is the complete private operator interface. Public Markdown
# is intentionally narrower: only offline workflows that a developer can run
# without fleet access, credentials, or an attached arm are exported.
_PUBLIC_NOUNS = {"estop", "profile", "teleop", "rollout", "sim", "vision", "inkmap"}


def _public_text(value: str) -> str:
    """Remove deployment identities from generated public prose."""
    value = _PRIVATE_NODE.sub("configured host", value)
    value = re.sub(r"~?/[^ )`]+", "<path>", value)
    value = re.sub(r"\bconfig/training/[^ )`]+", "<manifest>", value)
    value = re.sub(r"--nonce(?:=|\s+)[^ )`]+", "--nonce <nonce>", value)
    value = re.sub(r"(?i)server on configured host", "server on a configured host", value)
    value = re.sub(r"(?i)configured host / configured host", "configured training hosts", value)
    value = re.sub(r"(?i)configured host's", "configured host's", value)
    value = re.sub(r"(?i)fleet generator", "local generator", value)
    value = re.sub(r"(?i)what the Space serves", "the generated web bundle", value)
    value = re.sub(r"(?i)run and read trained policies on the arm", "analyze policy rollouts and recorded data", value)
    value = re.sub(r"(?i)the Pico e-stop, bench-checked or simulated", "simulate and inspect e-stop interfaces", value)
    value = re.sub(r"(?i)cameras, calibration, tracking, deploy", "offline vision processing and calibration", value)
    return value


def as_dict(repo: Path) -> dict:
    nmap = nodes.load(repo)
    return {
        "version": __version__,
        "tiers": {t: {"meaning": TIER_MEANING[t], "gates": list(TIER_GATES[t])} for t in TIERS},
        "exit_codes": {str(k): v for k, v in EXIT_NAMES.items()},
        "nodes": nmap,
        "nouns": [{"noun": n, "summary": NOUN_SUMMARY.get(n, "")} for n in nouns()],
        "verbs": [{
            "name": v.name, "noun": v.noun, "verb": v.verb, "tier": v.tier, "summary": v.summary,
            "role": v.role, "nodes": nodes.nodes_with(nmap, v.role) if v.role else None,
            "gates": list(v.gates), "needs_tool": v.needs_tool, "nonce": v.nonce,
            "nonce_exempt": list(v.nonce_exempt), "dip_hook": v.dip_hook,
            "passthrough": v.passthrough, "wraps": list(v.wraps), "doc": v.doc,
            "invariants": list(v.invariants),
            "example": f"tatbot {v.name} {' '.join(v.example)}".strip(),
        } for v in all_verbs()],
    }


def as_json(repo: Path) -> str:
    return json.dumps(as_dict(repo), indent=2)


def as_markdown(repo: Path) -> str:
    """Render the public command reference.

    JSON remains the complete machine-readable schema for private automation.
    Markdown is a checked-in public page, so it must not expose node inventory,
    SSH targets, local paths, private plans, or internal example arguments.
    """
    d = as_dict(repo)
    out = []
    out.append("# `tatbot` command reference\n")
    out.append("<!-- GENERATED by `scripts/tatbot schema --md > docs/cli.md`. Do not edit; `scripts/check cli` fails when stale. -->\n")
    out.append("Offline CLI workflows for public development and replay. Maintainers can inspect the complete machine-readable schema with `tatbot schema --json`.\n")
    out.append("```\ntatbot [global flags] <noun> [verb] [args] [-- passthrough args]\n```\n")
    out.append("Global flags go **before** the noun: `--json`, `--dry-run`, `--explain`, `-q`, `-v`.\n")
    out.append("## Exit codes\n")
    out.append("| code | meaning |\n| --- | --- |")
    for k, v in d["exit_codes"].items():
        out.append(f"| {k} | {v} |")
    out.append("\n## Safety tiers\n")
    out.append("| tier | meaning | gates |\n| --- | --- | --- |")
    for t, rec in d["tiers"].items():
        if t != "offline":
            continue
        out.append(f"| `{t}` | {rec['meaning']} | {'; '.join(rec['gates']) or '—'} |")
    out.append("\n## Verbs\n")
    cur = None
    for v in d["verbs"]:
        if v["noun"] not in _PUBLIC_NOUNS or v["tier"] != "offline":
            continue
        if v["noun"] != cur:
            cur = v["noun"]
            summ = _public_text(next(x["summary"] for x in d["nouns"] if x["noun"] == cur))
            suffix = f" — {summ}" if summ else ""
            out.append(f"\n### `tatbot {cur}`{suffix}\n")
            out.append("| verb | tier | runs on | wraps | summary |\n| --- | --- | --- | --- | --- |")
        where = "this checkout"
        wraps = ", ".join(f"`{w}`" for w in v["wraps"]) or "native"
        name = f"`{v['name']}`"
        extras = []
        if v["needs_tool"]:
            extras.append("`--ee-tool`")
        if v["nonce"]:
            exempt = " / ".join(f"`--{d.replace('_', '-')}`" for d in v["nonce_exempt"])
            extras.append("`--nonce`" + (f" (not with {exempt})" if exempt else ""))
        if v["dip_hook"]:
            extras.append("`--dip` (needs `--nonce`) / `--no-ink`")
        if v["passthrough"]:
            extras.append(f"`--` → {v['passthrough']}")
        summ = _public_text(v["summary"] + (f" ({'; '.join(extras)})" if extras else ""))
        out.append(f"| {name} | `{v['tier']}` | {where} | {wraps} | {summ} |")
    out.append("\n## Examples\n")
    out.append("```")
    for v in d["verbs"]:
        if v["noun"] not in _PUBLIC_NOUNS or v["tier"] != "offline":
            continue
        # Examples are deliberately schematic: node names, tool IDs, paths,
        # and inventory identifiers are deployment-specific/private.
        args = []
        prefix_len = 1 + len(v["name"].split())
        for arg in v["example"].split()[prefix_len:]:
            if _PRIVATE_NODE.fullmatch(arg):
                args.append("<configured-node>")
            elif "tool" in arg or arg.startswith("picosecond-"):
                args.append("<tool-id>")
            elif arg.startswith("inkcap_") or arg.startswith("nighthawk_"):
                args.append("<inventory-id>")
            elif arg.startswith(("~/", "/", "<")):
                args.append("<path>")
            elif re.match(r"^\d{8}T\d{6}Z-", arg) or "run-id" in arg or _PRIVATE_NODE.search(arg):
                args.append("<run-id>")
            else:
                args.append(_public_text(arg))
        out.append(f"tatbot {v['name']} {' '.join(args)}".strip())
    out.append("```\n")
    return "\n".join(out)
