ip_address_l: 192.168.1.3
ip_address_r: 192.168.1.2
arm_l_config_filepath: ~/tatbot/config/trossen/arm_l.yaml
arm_r_config_filepath: ~/tatbot/config/trossen/arm_r.yaml
goal_time_fast: 0.08
goal_time_slow: 1.2
connection_timeout: 6.0
ee_rot_l:
  wxyz:
  - 0.7071
  - 0.0
  - 0.0
  - -0.7071
ee_rot_r:
  wxyz:
  - 0.7071
  - 0.0
  - 0.0
  - 0.7071
hover_offset:
  xyz:
  - 0.0
  - 0.0
  - 0.005
offset_range:
- -0.002
- 0.002
offset_num: 6
ee_offset_l:
  xyz:
  - 9.476485859916117e-08
  - -0.004921962697931922
  - -0.004
ee_offset_r:
  xyz:
  - 2.948005620728722e-07
  - 0.01531155526901514
  - 0.002
lasercross_len_mm: 180
