tasks:
  - task_name: "pick_cube_place_circle"
    robot_model: "trossen_ai_solo"
    task_description: "Pick up the red cube and place it in the blue circle."
    episode_length_s: 12
    num_episodes: 20
    warmup_time_s: 5
    reset_time_s: 5
    hf_user: "hu-po"
    fps: 30
    push_to_hub: true