image_width: 2960
image_height: 1668
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1669.99114,    0.     , 1472.80101,
            0.     , 1674.75258,  852.56832,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.328804, 0.084989, -0.000450, 0.000864, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1150.36731,    0.     , 1479.32136,    0.     ,
            0.     , 1521.18335,  855.39091,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]