[project]
name = "tatbot"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
    "psutil==5.9.0",
    "anthropic==0.49.0",
    "openai==1.73.0",
    "google-generativeai==0.8.4",
    "replicate==1.0.4",
    "aiofiles==24.1.0",
    "tenacity==9.1.2",
    "pyyaml==6.0.1",
    "rerun-sdk==0.23.2",
]

[tool.setuptools]
packages = ["tatbot"]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.4",
]