inkcaps:
  - name: left_large
    ink:
      name: nighthawk_black
      rgb: [0, 0, 0]
    diameter_m: 0.014
    depth_m: 0.014
  - name: right_large
    ink:
      name: nighthawk_black
      rgb: [0, 0, 0]
    diameter_m: 0.014
    depth_m: 0.014