import contextlib
import csv
import datetime as dt
import importlib.util
import logging
import os
import re
import signal
import sys
import time
from collections import deque
from pathlib import Path
from typing import Any

import trossen_arm
from lerobot.robots.utils import ensure_safe_goal_position
from lerobot.utils.errors import DeviceNotConnectedError
from lerobot_robot_trossen.widowxai_follower import WidowXAIFollower

from lerobot_robot_tatbot import (
    goldens,
    params,
    paths,
    recovery,
    runlog_shim,
    tool_registry,
    warn_throttle,
)
from lerobot_robot_tatbot.config_tatbot_follower import TatbotFollowerConfig
from lerobot_robot_tatbot.depth_encoding import encode_depth_mm
from lerobot_robot_tatbot.estop import EstopMonitor, acquire_estop, release_estop
from lerobot_robot_tatbot.motion_safety import MotionSafetyError, MotionSafetyWatchdog

logger = logging.getLogger(__name__)

VALUES_REFRESH_S = 5.0  # registry-value snapshot period (config reads are UDP)


TOOL_TIP_LINK = "right/tattoo_needle"  # generated by scripts/gen_tool_urdf.py
# Arm joint speed under which the contact cap is assessed (rad/s). Above it
# the carriage effort carries the EE chain's inertial load (+-18 N on the
# 2026-08-30 bench) and says nothing about contact. Drawing is slower.
CONTACT_STILL_RAD_S = 0.3


class TatbotFollower(WidowXAIFollower):
    """WidowX AI follower whose gripper carriage is the tool's contact axis.

    Since 2026-08-30 the tool sits in a bore on a mount bolted to the LEFT
    finger carriage (the right finger is removed), so the carriage moves the
    pen along its own axis: 0.0 — the closed hard stop — is the pen at rest,
    opening retracts it. Nothing is gripped, so the bounded-grip force law
    that lived here is gone. The carriage runs in POSITION mode like the arm
    joints and is owned by the safety layer, never by the leader or the
    policy: whatever the action says for the 7th channel, the sent carriage
    is this class's target (rest, or the retract). Its external effort is the
    pen's contact force, published as ``contact_force_n``; above
    ``carriage_contact_cap_n`` the pen is lifted first and the arm retreats
    after. The e-stop hold retracts it too. Because this lives in
    send_action, it applies identically to a human demo (lerobot-record) and
    a policy (lerobot-rollout), and the 7-dim dataset layout is unchanged.
    """

    config_class = TatbotFollowerConfig
    name = "tatbot_follower"

    GRIPPER = 6  # carriage joint index; joint_names[-1] is the carriage

    def __init__(self, config: TatbotFollowerConfig):
        # tatbot.yaml before super().__init__: the parent derives
        # min_time_to_move from loop_rate × multiplier at construction time.
        if config.use_tatbot_yaml:
            goldens.apply_section(
                config, goldens.load_tatbot_yaml().get("follower"))
            config.__post_init__()  # re-clamp after yaml values landed
        # Stated, not inferred: see TatbotFollowerConfig.ee_tool. Raises on a
        # missing or contradicted tool, before anything reaches the driver.
        self._tool = (
            tool_registry.stated_tool(
                config.ee_tool, context="tatbot follower connect")
            if config.use_tool_registry else None)
        super().__init__(config)
        self.config = config
        self._estop: EstopMonitor | None = None
        self._estop_hold: dict[str, float] | None = None
        # The carriage's commanded target (rest or retract) once staging has
        # seated it; None before that, in which case nothing touches it.
        self._carriage_target: float | None = None
        self._carriage_sent: float | None = None
        self._contact_n: int = 0
        self._contact_trip: bool = False
        self._contact_baseline_n: float = 0.0
        self._carriage_settled: bool = False
        self._overforce_hold: dict[str, float] | None = None
        self._overforce_t: float = 0.0
        self._overforce_n: int = 0
        self._pose_history: deque[tuple[float, dict[str, float]]] = deque()
        self._kin = None
        self._kin_joints: list[str] | None = None
        self._z_floor_warned: float = 0.0
        self._flight_log = None
        self._flight_writer = None
        self._cmd_target: dict[str, float] | None = None
        self._cmd_time: float | None = None
        self._filt_target: dict[str, float] | None = None
        self._tuning = None  # TuningShared once registered
        self._tuning_server = None
        self._values_published = 0.0
        self._scale_state: dict | None = None  # motion-scale anchors
        self._clamp_throttle = None
        self._watchdog = recovery.TrackingWatchdog()
        self._motion_watchdog = MotionSafetyWatchdog.from_config(config)
        # Set by a coordinated startup so every arm lifts at once instead of
        # each plugin blocking through its own staged move.
        self.defer_staging = False
        self._pending_stage: list[float] | None = None

    def configure(self) -> None:
        # What is actually driving the arm, recorded before anything moves.
        self._report_versions()
        # Hardware e-stop first: refuse to start moving (the staged-pose move
        # below) while the button is latched or the heartbeat is missing.
        if self._estop is not None:
            release_estop(self._estop)
            self._estop = None
        if self.config.estop_required and not self.config.estop_device:
            # Reachable since the profile refactor: an unresolvable profile
            # defaults the device to "" while required stays True. Refuse —
            # never move arms unmonitored because a config file was absent.
            raise RuntimeError(
                "estop_required=True but no e-stop device resolved from the "
                "hardware profile — fix TATBOT_PROFILE/config/profiles, or "
                "set estop_required=False for an explicit hardware-free bench")
        if self.config.estop_device:
            self._estop = acquire_estop(
                self.config.estop_device, required=self.config.estop_required
            )
            if self._estop is not None:
                self._estop.wait_for_initial_state()
                if self._estop.engaged:
                    state = self._estop.state.value
                    release_estop(self._estop)
                    self._estop = None
                    raise RuntimeError(
                        f"e-stop engaged ({state}) — twist-release "
                        "the button (or reconnect the box) and retry"
                    )
        # Golden arm config: write the follower's parameters into the
        # controller (its state is scratch RAM — without this, sessions run
        # on whatever the last process or power cycle left behind). Applied
        # field-by-field via driver setters — NOT load_configs_from_file,
        # which also rewrites network EEPROM every connect and hard-fails on
        # YAML schema drift between driver versions. The end-effector preset
        # is then asserted from the SDK, exactly like cpp/teleop, so gravity
        # comp always matches the hardware.
        if self.config.arm_config != "-":
            arm_yaml = (
                Path(self.config.arm_config).expanduser()
                if self.config.arm_config
                else goldens.config_dir() / "follower.yaml"
            )
            if arm_yaml.exists():
                applied = goldens.apply_arm_golden(
                    self.driver, trossen_arm, arm_yaml
                )
                self.driver.set_end_effector(
                    trossen_arm.StandardEndEffector.wxai_v0_follower
                )
                logger.info(
                    f"{self} applied golden {arm_yaml} ({', '.join(applied)})"
                )
            else:
                logger.warning(
                    f"{self} golden arm config {arm_yaml} missing — running "
                    "on the controller's current state"
                )
        # Preflight: refuse to command motion on a controller that is still
        # faulted (clear_error at connect does not always recover a wedged
        # firmware — driving it anyway is how an arm ends up frozen).
        err = recovery.controller_error(self.driver)
        if err:
            raise RuntimeError(
                f"{self} controller reports a firmware error after connect: "
                f"{err!r} — power-cycle the arm"
            )
        # Resolve and validate the current-session floor before the first staged
        # move. Previously the resolver only ran from _apply_z_floor, while that
        # caller was gated on z_floor_m already being non-null: the preferred
        # surface-relative configuration therefore never switched the floor on.
        floor_requested = (
            self.config.z_floor_m is not None
            or self.config.z_floor_below_surface_m is not None
        )
        floor_ready = bool(floor_requested and self._kinematics() is not None)
        if self.config.require_z_floor and not (
            floor_ready and self.config.z_floor_m is not None
        ):
            raise RuntimeError(
                "a valid current-session tool-tip workspace floor is required; "
                "run touch-off, verify the fitted-tool URDF, and retry"
            )
        if self.config.require_z_floor:
            self._validate_floor_receipt()
        # Stock behavior next: all-position modes and move to staged pose.
        # Upstream's configure() is those two calls; they are inlined so a
        # coordinated startup can move every arm at once instead of each
        # plugin blocking through its own lift.
        staged = list(self.config.staged_positions)
        self._carriage_target = None
        self._carriage_sent = None
        self.driver.set_all_modes(trossen_arm.Mode.position)
        if self.defer_staging or self.config.coordinated_arms:
            # Pin the target where the arm stands before stepping away:
            # position mode with an uncommanded target can jerk toward a
            # stale one when torque enables.
            with contextlib.suppress(Exception):
                self.driver.set_all_positions(
                    list(self.driver.get_all_positions()),
                    recovery.TAKEOVER_S, False,
                )
            recovery.arm_group.register(
                "follower", self, self.driver, staged, self.GRIPPER,
                estop=self._estop,
            )
            self._pending_stage = staged
            return
        self._pending_stage = staged
        recovery.raise_arms_together(
            [("follower", self.driver, staged, self.GRIPPER)],
            goal_time=2.0,
            estop=self._estop,
        )
        self.finish_staging()

    def finish_staging(self) -> None:
        """Verify the staged move and complete configuration."""
        # The staged move is blocking but unverified: confirm the arm
        # actually executed it before we start streaming teleop commands.
        recovery.assert_controller_healthy(
            self.driver, self._pending_stage or list(self.config.staged_positions),
            str(self),
        )
        self._pending_stage = None
        # The carriage stays in position mode with the rest of the arm; seat
        # it at rest and keep it there. Only the safety layer moves it after.
        self._set_carriage(self.config.carriage_rest_m, 1.0)
        # Rest baseline of the carriage effort: what the contact cap measures
        # departure from. Median of settled readings — a single sample taken
        # right at the end of the staged move reads the motor still
        # decelerating (a -5.6 N baseline tripped a phantom contact cap on
        # the first safety-pause resume, 2026-08-31, and a junk baseline
        # never clears: the trip's release needs contact under half the cap).
        with contextlib.suppress(Exception):
            deadline = time.monotonic() + 2.5
            while time.monotonic() < deadline:
                position = float(
                    self.driver.get_robot_output().joint.all.positions[self.GRIPPER])
                if abs(position - self.config.carriage_rest_m) < 0.0005:
                    break
                time.sleep(0.05)
            readings = []
            for _ in range(5):
                readings.append(float(
                    self.driver.get_robot_output().joint.all.external_efforts[self.GRIPPER]))
                time.sleep(0.05)
            self._contact_baseline_n = float(sorted(readings)[len(readings) // 2])
        self._apply_controller_velocity_limit()
        logger.info(
            f"{self} carriage at rest {self.config.carriage_rest_m * 1000:.1f} mm; contact cap "
            f"{self.config.carriage_contact_cap_n:.1f} N -> retract "
            f"{self.config.carriage_retract_m * 1000:.0f} mm"
            + (f" (tool {self._tool.tool_id})" if self._tool else "")
        )
        self._cmd_target = None
        self._cmd_time = None
        self._filt_target = None
        self._finish_staging_runtime()

    def _apply_controller_velocity_limit(self) -> None:
        """Install the opt-in controller-side commissioning speed cap."""
        vel_limit = getattr(self.config, "controller_velocity_limit", None)
        if vel_limit is not None:
            limit = float(vel_limit)
            if limit <= 0:
                raise ValueError("controller_velocity_limit must be positive")
            joint_limits = self.driver.get_joint_limits()
            for joint in range(self.GRIPPER):
                joint_limits[joint].velocity_max = limit
            self.driver.set_joint_limits(joint_limits)
            logger.warning(
                "%s controller arm velocity_max commissioned at %.2f rad/s",
                self,
                limit,
            )
            runlog_shim.event(
                "controller_velocity_limit", arm="follower", limit_rad_s=limit
            )

    def _finish_staging_runtime(self) -> None:
        """Continue finish_staging after controller/gripper safety setup."""
        # Upstream logs a multi-line clamp WARNING on every tick it bites, and
        # the staged -> policy-pose traverse bites for ~1.5 s (~30 warnings on
        # every run of the 2026-08-21 sweep). Summarize the repeats; the clamp
        # itself is untouched, and one warning still gets through every 10 s
        # because a clamp biting after the transient is a real signal.
        self._clamp_throttle = warn_throttle.install()
        logger.info(
            f"{self} startup transient: the policy will pull the arm off the staged "
            "pose and max_relative_target will clamp for ~1-2 s. Expected. "
            "Analysis should skip the first 8 s (il_analyze_rollout.py does)."
        )
        path = self._flight_log_path()
        if path is not None:
            path.parent.mkdir(parents=True, exist_ok=True)
            # buffering=1 (line buffered): each row reaches the kernel as it is
            # written, so a SIGKILL or a wedged controller costs the row in
            # flight instead of the whole tail — and the rows nearest a failure
            # are the only ones anybody ever wants. One write per row at 30 Hz
            # is free. Do NOT port this to the 400 Hz C++ recorder unmeasured.
            self._flight_log = open(path, "w", newline="", buffering=1)  # noqa: SIM115 — lives until disconnect()
            self._flight_writer = csv.writer(self._flight_log)
            joints = self.config.joint_names
            self._flight_writer.writerow(
                ["t_wall", "t_mono", "goal_time", "contact_force_n"]
                + [f"raw_{j}" for j in joints]
                + [f"goal_{j}" for j in joints]
                + [f"pos_{j}" for j in joints]
                + [f"vel_{j}" for j in joints]
                + [f"eff_{j}" for j in joints]
            )
            logger.info(f"{self} flight recorder: {path}")
            runlog_shim.artifact(path, kind="flight_csv", robot=self.config.id)
        self._scale_state = None
        self._watchdog = recovery.TrackingWatchdog()
        self._motion_watchdog.reset(time.monotonic())
        # Tuning cockpit: register this rig's parameters with the in-process
        # server (created on first registration; the leader shares it).
        if self.config.tuning_enabled and self.config.tuning_port > 0:
            from lerobot_robot_tatbot.tuning_server import get_shared_server

            self._tuning_server = get_shared_server(self.config.tuning_port)
            self._tuning = self._tuning_server.register(
                "follower",
                params.build_follower_params(
                    self.driver, self.config, trossen_arm, robot=self
                ),
                self.config,
                robot=self,
            )
            self._tuning.publish_values()
            self._values_published = time.monotonic()

    def _kinematics(self):
        """Forward kinematics for the floor, loaded once from the rig URDF.

        Uses the calibration stack's UrdfChain (scripts/vision/
        urdf_kinematics.py) so the repo has ONE forward-kinematics
        implementation — the same one the touch-off solver and the rollout
        analyzer trust. Loaded by file path because scripts/ is not an
        installed package; this plugin already depends on the repo checkout
        for the URDF and golden configs, so the path is no new assumption.
        """
        if self._kin is None:
            repo = paths.repo_root()
            urdf = repo / self.config.z_floor_urdf
            fk_py = repo / "scripts" / "vision" / "urdf_kinematics.py"
            missing = next((p for p in (urdf, fk_py) if not p.exists()), None)
            if missing is not None:
                logger.error(
                    "z_floor_m is set but %s is missing — WORKSPACE FLOOR IS OFF", missing
                )
                self.config.z_floor_m = None
                return None
            spec = importlib.util.spec_from_file_location("tatbot_urdf_kinematics", fk_py)
            if spec is None or spec.loader is None:
                logger.error(
                    "cannot load tatbot_urdf_kinematics from %s — WORKSPACE FLOOR IS OFF", fk_py
                )
                self.config.z_floor_m = None
                self.config.z_floor_below_surface_m = None
                return None
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            self._kin = mod.UrdfChain(urdf)
            self._kin_joints = [
                f"right/{j}" for j in self.config.joint_names[: self.GRIPPER]
            ]
            # The floor reads the TIP out of this URDF's generated tool block.
            # A block for a different tool would put the tip somewhere the tool
            # is not, which is under-protection wearing the same log line — so
            # refuse rather than measure the wrong point.
            stale = self._tool_block_mismatch(urdf)
            if stale is not None:
                logger.error("%s — WORKSPACE FLOOR IS OFF", stale)
                self.config.z_floor_m = None
                self.config.z_floor_below_surface_m = None
                self._kin = None
                return None
            # Membership, not a try/except: UrdfChain.link_pose walks parents
            # and returns IDENTITY for a link it does not know, so a missing
            # tip would silently read z=0 and the floor would compare the
            # commanded pose against the origin.
            if TOOL_TIP_LINK not in self._kin.parent_of:
                logger.error(
                    "%s has no %s link (run scripts/gen_tool_urdf.py) — "
                    "WORKSPACE FLOOR IS OFF", urdf, TOOL_TIP_LINK)
                self.config.z_floor_m = None
                self.config.z_floor_below_surface_m = None
                self._kin = None
                return None
            if not self._resolve_floor():
                self._kin = None
                return None
        return self._kin

    def _tool_block_mismatch(self, urdf) -> str | None:
        """Is the URDF's generated tool block the tool that is actually fitted?

        gen_tool_urdf.py stamps the datasheet name and hash into the block's
        header comment, so this is a direct comparison rather than a guess.
        Returns a reason to refuse, or None when they agree.
        """
        if self._tool is None:
            return None  # no tool registry in play; nothing to contradict
        try:
            text = Path(urdf).read_text()
        except OSError as error:
            return f"cannot read {urdf}: {error}"
        found = re.search(
            r"datasheet config/tools/([\w.-]+)\.yaml sha256 ([0-9a-f]+)", text)
        if found is None:
            return (f"{urdf} has no generated tool block "
                    f"(run scripts/gen_tool_urdf.py)")
        urdf_tool, urdf_sha = found.group(1), found.group(2)
        if urdf_tool != self._tool.tool_id:
            return (f"{urdf} was generated for {urdf_tool!r} but "
                    f"{self._tool.tool_id!r} is fitted — the floor would "
                    f"measure the wrong tool's tip; run scripts/gen_tool_urdf.py")
        if not self._tool.sha256.startswith(urdf_sha):
            return (f"{urdf}'s tool block is stale for {urdf_tool!r} "
                    f"(datasheet has changed) — run scripts/gen_tool_urdf.py")
        return None

    def _resolve_floor(self) -> bool:
        """Settle the floor into config.z_floor_m as an absolute TIP height.

        Preferring the measured surface is what lets the table move: the
        touch-off writes wherever it actually is (which may be below the robot
        base, hence no sign assumption), and the deliberate constant is the
        clearance beneath it rather than a height that silently goes stale.
        """
        below = self.config.z_floor_below_surface_m
        if below is None:
            if self.config.z_floor_m is None:
                logger.warning("no workspace floor configured — FLOOR IS OFF")
                return False
            logger.info("workspace floor active: tool TIP held at or above "
                        "z=%.3f m (absolute, no surface reference)",
                        self.config.z_floor_m)
            return True
        surface = None
        reg = tool_registry.registry()
        if reg is not None:
            side = (reg.read_workspace(tool_registry.REPO) or {}).get("right") or {}
            surface = side.get("paper_plane_z")
        if surface is None:
            if self.config.z_floor_m is None:
                logger.error(
                    "z_floor_below_surface_m is set but config/workspace.yaml "
                    "has no measured surface, and no absolute z_floor_m to fall "
                    "back to — WORKSPACE FLOOR IS OFF. Run a touch-off.")
                return False
            logger.warning(
                "no measured surface in config/workspace.yaml; falling back to "
                "absolute z_floor_m=%.3f m", self.config.z_floor_m)
            return True
        self.config.z_floor_m = float(surface) - float(below)
        logger.info(
            "workspace floor active: tool TIP held at or above z=%.3f m "
            "(measured surface %.3f m - %.0f mm clearance)",
            self.config.z_floor_m, float(surface), float(below) * 1000)
        return True

    def _validate_floor_receipt(self) -> None:
        """Require a fitted-tool pad touch-off from the current work session."""
        reg = tool_registry.registry()
        workspace = reg.read_workspace(tool_registry.REPO) if reg is not None else None
        side = (workspace or {}).get("right") or {}
        receipt = side.get("touchoff") or {}
        if int(receipt.get("n_pad") or 0) <= 0:
            raise RuntimeError(
                "required workspace floor has no paper-pad touch; run a current touch-off"
            )
        raw_utc = receipt.get("utc")
        if not raw_utc:
            raise RuntimeError(
                "required workspace floor has no touch-off timestamp; run a current touch-off"
            )
        try:
            touched = dt.datetime.fromisoformat(str(raw_utc).replace("Z", "+00:00"))
            age_s = (dt.datetime.now(dt.UTC) - touched.astimezone(dt.UTC)).total_seconds()
        except (TypeError, ValueError) as error:
            raise RuntimeError(
                f"required workspace floor has invalid touch-off timestamp {raw_utc!r}"
            ) from error
        maximum = float(self.config.z_floor_max_age_s)
        if age_s < -300:
            raise RuntimeError("workspace floor touch-off timestamp is in the future")
        if maximum > 0 and age_s > maximum:
            raise RuntimeError(
                f"workspace floor touch-off is {age_s / 3600:.1f} h old; "
                f"powered policy limit is {maximum / 3600:.1f} h — touch off again"
            )
        runlog_shim.event(
            "workspace_floor",
            z_floor_m=self.config.z_floor_m,
            touch_off_utc=str(raw_utc),
            touch_off_age_s=age_s,
            touch_off_session=receipt.get("session"),
            tool=side.get("tool_id"),
        )

    def _tool_z(self, kin, pose: dict[str, float]) -> float:
        if self._kin_joints is None:
            return 0.0
        q = {
            n: pose[j]
            for n, j in zip(
                self._kin_joints,
                self.config.joint_names[: self.GRIPPER],
                strict=True,
            )
        }
        # The mount rides the carriage, so the tip's height depends on it:
        # a retracted pen is a lifted tip, and the floor must see that.
        carriage = self.config.joint_names[self.GRIPPER]
        q[f"right/{carriage}"] = float(pose.get(carriage, getattr(self.config, "carriage_rest_m", 0.0)))
        # The TIP, not the gripper base. Until 2026-08-26 this returned
        # ee_gripper_link, so the "workspace floor" never saw the tool at all
        # and its constant carried one particular pen's length by accident.
        # The generated tool block puts the tip where the touch-off measured
        # it, so length AND wrist orientation are handled by geometry.
        return float(kin.link_pose(TOOL_TIP_LINK, q)[2, 3])

    def _set_carriage(self, target_m: float, goal_time: float) -> None:
        """Move the carriage to ``target_m`` (position mode), once per change.

        The only writer of the carriage. Rest at staging, the retract on an
        e-stop or a contact trip, rest again when it clears — nothing else,
        and never the leader or the policy.
        """
        target_m = float(target_m)
        self._carriage_target = target_m
        if self._carriage_sent is not None and abs(self._carriage_sent - target_m) < 1e-6:
            return
        self.driver.set_joint_position(self.GRIPPER, target_m, float(goal_time), False)
        self._carriage_sent = target_m
        # not settled until it has been seen within tolerance of the new target
        self._carriage_settled = False

    def _preserve_carriage(self, rewritten: dict, goal_pos: dict) -> dict:
        """Apply a safety guard's rewrite of the goal to the ARM only.

        The carriage entry is the safety layer's target, not a pose the guard
        may reason about: dragging it toward `present` would ride the pen
        back down its axis in the middle of a retract, or lift it during
        ordinary drawing. The mirror image of the gripper-era invariant (a
        guard that pressed too hard must not let go); the C++ teleop holds
        the same line.
        """
        gripper = self.config.joint_names[self.GRIPPER]
        target = self._carriage_target
        return {**rewritten, gripper: goal_pos[gripper] if target is None else target}

    def _apply_z_floor(
        self, goal_pos: dict[str, float], present: dict[str, float]
    ) -> dict[str, float]:
        kin = self._kinematics()
        if kin is None:
            return goal_pos
        floor = self.config.z_floor_m
        if floor is None:
            return goal_pos
        if self._tool_z(kin, goal_pos) >= floor:
            return goal_pos
        # Largest fraction of the commanded motion that stays above the floor.
        # Bisection rather than a closed form: z is not linear in joint angles.
        # Scale the ARM only: the carriage is the safety layer's, and its
        # target is already in goal_pos (see _preserve_carriage).
        gripper_joint = self.config.joint_names[self.GRIPPER]
        arm = [j for j in goal_pos if j != gripper_joint]
        lo, hi = 0.0, 1.0
        for _ in range(12):
            mid = (lo + hi) / 2
            probe = {**goal_pos,
                     **{j: present[j] + mid * (goal_pos[j] - present[j]) for j in arm}}
            if self._tool_z(kin, probe) >= floor:
                lo = mid
            else:
                hi = mid
        now = time.monotonic()
        if now - self._z_floor_warned > 1.0:
            self._z_floor_warned = now
            logger.warning(
                "Z-FLOOR: commanded tool z %.3f m below floor %.3f m — allowing %.0f%% "
                "of the requested motion",
                self._tool_z(kin, goal_pos), floor, lo * 100,
            )
        return self._preserve_carriage(
            {j: present[j] + lo * (goal_pos[j] - present[j]) for j in arm}, goal_pos)

    def send_action(self, action: dict[str, Any]) -> dict[str, Any]:
        if not self.is_connected:
            raise DeviceNotConnectedError(f"{self} is not connected.")
        # Never let the deferred staged move run while stopped. ArmGroup also
        # monitors the heartbeat throughout the move, closing the race between
        # this check and the first interpolation command.
        if self._estop is None or not self._estop.engaged:
            self._ensure_staged()

        goal_pos = {
            key.removesuffix(".pos"): val
            for key, val in action.items()
            if key.endswith(".pos")
        }
        raw_goal = dict(goal_pos)
        # The carriage is not the leader's or the policy's to command (plan
        # decisions D2/D3, 2026-08-30): whatever the action's 7th channel
        # says, the sent carriage is the safety layer's target.
        gripper_joint = self.config.joint_names[self.GRIPPER]
        if self._carriage_target is not None:
            goal_pos[gripper_joint] = self._carriage_target

        joint_state = self.driver.get_robot_output().joint.all
        present = dict(
            zip(self.config.joint_names, joint_state.positions, strict=True)
        )
        # The pen's contact force: the carriage effort's departure from its
        # rest baseline (taken at staging). Coarse — the estimate wanders
        # -12..+10 N even at rest and swings +-18 N during fast free moves
        # (bench, 2026-08-30) — so it is assessed only at drawing speeds and
        # debounced; it catches a hard press, not light contact. The position
        # hold is too stiff for deflection to be readable (0.02 mm under a
        # hand push), so effort is what there is.
        carriage_effort_n = float(joint_state.external_efforts[self.GRIPPER])
        contact_n = abs(carriage_effort_n - getattr(self, "_contact_baseline_n", 0.0))
        arm_speed = max(abs(v) for v in joint_state.velocities[: self.GRIPPER])
        contact_assessable = arm_speed < CONTACT_STILL_RAD_S
        # With a compliant carriage, deflection OPEN off the target is the
        # cleaner contact signal (millimetres under a push, 0.05 mm otherwise).
        deflect_m = (
            float(joint_state.positions[self.GRIPPER]) - self._carriage_target
            if self._carriage_target is not None else 0.0)
        # A deflection only means contact once the carriage has SETTLED on its
        # target (the seat from a retracted start takes a second; on
        # 2026-08-30 the check ran at the first tick, read the 40 mm the last
        # session's abort had left, tripped, retracted — and the deflection
        # then stayed 40 mm forever, holding the arm in the retreat for the
        # whole session). And it only means contact while the target is REST:
        # a retracted carriage is 40 mm off rest by design.
        if self._carriage_target is not None and abs(deflect_m) < 0.0005:
            self._carriage_settled = True
        deflect_assessable = (
            getattr(self, "_carriage_settled", False)
            and self._carriage_target is not None
            and abs(self._carriage_target - self.config.carriage_rest_m) < 1e-6)

        # Hardware e-stop: while engaged, the incoming action is discarded and
        # the arm holds the poses measured at engage time, with the pen
        # retracted along its axis (see _enter_estop_hold). Applies
        # identically to human demos and policy rollouts, since both flow
        # through send_action. On release, actions resume — any accumulated
        # leader/policy offset is stepped through max_relative_target's clip.
        estop_engaged = self._estop is not None and self._estop.engaged
        if estop_engaged:
            if self._estop_hold is None:
                self._enter_estop_hold(present)
                if getattr(self.config, "abort_on_estop", False):
                    estop_state = self._estop.state.value if self._estop is not None else "engaged"
                    raise RuntimeError(
                        f"E-stop engaged ({estop_state}); policy inference aborted"
                    )
            # The hold already froze the arm joints in position mode at their
            # measured poses and retracted the carriage; nothing further may
            # be written to any joint while it lasts.
            estop_hold = self._estop_hold
            if estop_hold is not None:
                return {
                    f"{joint}.pos": val for joint, val in estop_hold.items()
                }
            return {}
        if self._estop_hold is not None:
            self._leave_estop_hold(present)

        # Tuning changes wait behind the safety hold. Some controller writes
        # can block; none may delay the first measured-pose command after a
        # press or heartbeat fault.
        if not estop_engaged and self._tuning is not None:
            self._tuning.apply_pending("follower", joint_state.velocities)
            now_mono = time.monotonic()
            if now_mono - self._values_published > VALUES_REFRESH_S:
                self._tuning.publish_values()
                self._values_published = now_mono

        # Contact cap on the carriage's own signals. Bench 2026-08-30: the
        # carriage lead screw is self-locking, so a push neither moves it
        # (0.19 mm, and it stays) nor loads the motor for long; this cap will
        # only ever see a gross event. The joint-torque overforce guard below
        # is the real contact detector and ALSO retracts the carriage; both
        # share _contact_trip so the pen returns to rest once the load clears.
        if not estop_engaged and self._carriage_target is not None:
            cap = self.config.carriage_contact_cap_n
            pushed = (contact_assessable and contact_n > cap) or (
                deflect_assessable and deflect_m > self.config.carriage_contact_deflect_m)
            self._contact_n = self._contact_n + 1 if pushed else 0
            if (
                not self._contact_trip
                and self._contact_n >= self.config.carriage_cap_debounce
            ):
                self._contact_trip = True
                self._set_carriage(self.config.carriage_retract_m, 0.15)
                self._overforce_hold = (
                    dict(self._pose_history[0][1]) if self._pose_history else dict(present)
                )
                self._overforce_t = time.monotonic()
                self._overforce_n = max(self._overforce_n, self.config.overforce_debounce)
                logger.warning(
                    "CONTACT CAP: %.1f N over the rest baseline (%.1f N; raw %.1f N; cap %.1f N), "
                    "carriage deflected %.2f mm (limit %.2f mm) for %d steps: pen retracted "
                    "%.0f mm, arm retreating, actions ignored until the load clears",
                    contact_n, getattr(self, "_contact_baseline_n", 0.0), carriage_effort_n, cap,
                    deflect_m * 1000, self.config.carriage_contact_deflect_m * 1000,
                    self._contact_n, self.config.carriage_retract_m * 1000,
                )
                runlog_shim.event(
                    "contact_cap", force_n=contact_n, deflect_m=deflect_m,
                    baseline_n=getattr(self, "_contact_baseline_n", 0.0),
                    carriage_effort_n=carriage_effort_n, cap_n=cap, arm="follower",
                    retract_m=self.config.carriage_retract_m,
                )
            elif (
                self._contact_trip
                and self._overforce_hold is None
                and abs(contact_n) < 0.5 * cap
            ):
                self._contact_trip = False
                self._contact_n = 0
                self._set_carriage(
                    self.config.carriage_rest_m, self.config.carriage_goal_time_s)
                logger.warning("contact cap cleared (%.1f N): carriage back to rest", contact_n)

        # Overforce guard: a runaway press (policy driving into the table)
        # escalates external effort far beyond the demo envelope and stalls
        # the controller's comm loop.
        #
        # Retreat, do not latch in place. Holding the pose the arm is already
        # pressed into stops the press escalating but never relieves the load,
        # which on 2026-08-21 still cost an end effector. Instead go back to
        # where the arm was before the press developed, which lifts the tool
        # off whatever it is leaning on. A short debounce keeps ordinary
        # drawing spikes from tripping it.
        if not estop_engaged and self.config.overforce_limit > 0:
            over = max(
                abs(e) for e in joint_state.external_efforts[: self.GRIPPER]
            )
            now_of = time.monotonic()
            self._pose_history.append((now_of, dict(present)))
            cutoff = now_of - max(self.config.overforce_retreat_s, 0.0)
            while len(self._pose_history) > 2 and self._pose_history[1][0] < cutoff:
                self._pose_history.popleft()
            if over > self.config.overforce_limit:
                self._overforce_t = now_of
                self._overforce_n += 1
                if (
                    self._overforce_hold is None
                    and self._overforce_n >= max(self.config.overforce_debounce, 1)
                ):
                    # oldest pose still in the window: before the press built up
                    self._overforce_hold = dict(self._pose_history[0][1])
                    # The wrist efforts are the contact signal this rig has
                    # (bench 2026-08-30: a hard push on the pen read 3-4 Nm on
                    # joint 3 and nothing usable on the carriage — its lead
                    # screw is self-locking). Lift the pen along its axis
                    # first, then retreat the arm.
                    if self._carriage_target is not None and not self._contact_trip:
                        self._contact_trip = True
                        self._set_carriage(self.config.carriage_retract_m, 0.15)
                    logger.warning(
                        "OVERFORCE %.1f Nm > %.1f for %d steps: retreating %.2fs "
                        "of motion, actions ignored until load < %.1f Nm",
                        over, self.config.overforce_limit, self._overforce_n,
                        self.config.overforce_retreat_s,
                        self.config.overforce_release,
                    )
            elif (
                self._overforce_hold is not None
                and over < self.config.overforce_release
                and now_of - self._overforce_t > self.config.overforce_hold_s
            ):
                self._overforce_hold = None
                self._overforce_n = 0
                logger.warning(
                    "overforce cleared (%.1f Nm): resuming commanded actions",
                    over,
                )
            if over <= self.config.overforce_limit and self._overforce_hold is None:
                self._overforce_n = 0
            if self._overforce_hold is not None:
                # ARM ONLY: the retreat pose's carriage entry is whatever the
                # carriage read back then, and the carriage is not the guard's
                # to move (see _preserve_carriage) — mid-retract it must keep
                # retracting.
                goal_pos = self._preserve_carriage(
                    self._overforce_hold, goal_pos)

        # Workspace floor: refuse any commanded pose that would put the tool
        # below z_floor_m. Preventive, not reactive — the overforce guard only
        # acts once the arm is already loaded, and depth is explicitly not the
        # policy's job (nothing in sim resists the tool). Motion is scaled back
        # along the commanded delta, so travel parallel to the surface survives
        # and only the descent is truncated.
        if not estop_engaged and self.config.z_floor_m is not None:
            goal_pos = self._apply_z_floor(goal_pos, present)

        # Same safety clip as upstream. NOTE (pairing invariant): the dataset
        # stores the pre-clip action, so max_relative_target must stay outside
        # the normal demonstration envelope — audit early datasets for clips.
        clamped = False
        if self.config.max_relative_target is not None:
            before_clip = dict(goal_pos)
            goal_present = {k: (g, present[k]) for k, g in goal_pos.items()}
            goal_pos = ensure_safe_goal_position(
                goal_present, self.config.max_relative_target
            )
            clamped = any(
                abs(goal_pos[joint] - before_clip[joint]) > 1e-9
                for joint in self.config.joint_names[: self.GRIPPER]
            )

        arm_joints = self.config.joint_names[: self.GRIPPER]
        now = time.monotonic()
        try:
            self._motion_watchdog.update(
                now=now,
                velocities=joint_state.velocities[: self.GRIPPER],
                external_efforts=joint_state.external_efforts[: self.GRIPPER],
                clamped=clamped,
            )
        except MotionSafetyError as abort:
            self._hard_abort(present, abort)
            raise
        # Velocity slew limiter: the SENT target can never move faster than
        # max_joint_velocity, no matter what the policy/chunking layer emits.
        # This is what makes chunk-handoff reversals and out-of-distribution
        # jumps physically gentle — the firmware only ever sees demo-scale
        # steps, far below its ~9.4 rad/s trip. (An adaptive goal-time was
        # tried first and failed: it scaled with distance but ignored the
        # arm's current velocity, so reversals at speed still tripped.)
        dt = 1.0 / self.config.loop_rate
        if self._cmd_time is not None:
            dt = min(max(now - self._cmd_time, 0.005), 0.1)
        self._cmd_time = now
        if self._cmd_target is None:
            self._cmd_target = {j: present[j] for j in arm_joints}
        # Low-pass the requested target first (tremor from chunk aggregation
        # averages toward the policy's mean intent), then slew-limit.
        if self.config.target_filter_tau > 0:
            alpha = dt / (self.config.target_filter_tau + dt)
            if self._filt_target is None:
                self._filt_target = {j: present[j] for j in arm_joints}
            for j in arm_joints:
                self._filt_target[j] += alpha * (goal_pos[j] - self._filt_target[j])
            request = self._filt_target
        else:
            request = goal_pos
        request = self._apply_motion_scale(request, arm_joints)
        budget = self.config.max_joint_velocity * dt
        for j in arm_joints:
            delta = request[j] - self._cmd_target[j]
            self._cmd_target[j] += max(-budget, min(budget, delta))
            # Never let the sent target run far ahead of a blocked/lagging arm.
            if self.config.max_relative_target is not None:
                lo = present[j] - self.config.max_relative_target
                hi = present[j] + self.config.max_relative_target
                self._cmd_target[j] = max(lo, min(hi, self._cmd_target[j]))
        goal_time = self.min_time_to_move
        self.driver.set_arm_positions(
            [self._cmd_target[j] for j in arm_joints],
            goal_time=goal_time,
            blocking=False,
        )
        sent = dict(goal_pos)
        sent.update(self._cmd_target)

        # Tracking watchdog: a wedged controller ignores commands until the
        # max_relative_target clamp saturates and never physically moves.
        # (Error alone can't be the test — it also saturates when the
        # operator outruns the slew limiter, so the watchdog additionally
        # requires that the arm made no progress; see TrackingWatchdog.)
        if self._estop is None or not self._estop.engaged:
            worst = max(
                abs(self._cmd_target[j] - present[j]) for j in arm_joints
            )
            self._watchdog.update(
                worst, [present[j] for j in arm_joints], now, self.driver
            )

        # The carriage was already sent by _set_carriage whenever its target
        # changed; nothing writes to it per tick.
        if self._flight_writer is not None:
            joints = self.config.joint_names
            self._flight_writer.writerow(
                [f"{time.time():.6f}", f"{time.monotonic():.6f}",
                 f"{goal_time:.3f}", f"{contact_n:.2f}"]
                + [f"{raw_goal.get(j, float('nan')):.5f}" for j in joints]
                + [f"{sent[j]:.5f}" for j in joints]
                + [f"{p:.5f}" for p in joint_state.positions]
                + [f"{v:.5f}" for v in joint_state.velocities]
                + [f"{e:.3f}" for e in joint_state.external_efforts]
            )

        if self._tuning is not None:
            joints = self.config.joint_names
            self._tuning.publish("follower", {
                "joints": list(joints),
                "positions": [float(p) for p in joint_state.positions],
                "velocities": [float(v) for v in joint_state.velocities],
                "external_efforts": [
                    float(e) for e in joint_state.external_efforts
                ],
                "sent": [float(sent[j]) for j in joints],
                "tracking_error": [
                    float(sent[j] - present[j]) for j in joints
                ],
                "contact_force_n": float(contact_n),
                "carriage_effort_n": float(carriage_effort_n),
                "carriage_deflect_m": float(deflect_m),
                "contact_cap_n": float(self.config.carriage_contact_cap_n),
                "carriage_target_m": (
                    float(self._carriage_target) if self._carriage_target is not None
                    else float(joint_state.positions[self.GRIPPER])
                ),
                "goal_time": float(goal_time),
                "estop": (
                    self._estop.state.value if self._estop is not None
                    else "disabled"
                ),
            })

        return {f"{joint}.pos": val for joint, val in sent.items()}

    def get_observation(self) -> dict[str, Any]:
        # Recording and rollout code can keep observing while no new action is
        # sent. Poll the supervisor here too so that path still enters the
        # powered hold instead of relying on send_action timing.
        if self.is_connected and self._estop is not None:
            if self._estop.engaged and self._estop_hold is None:
                present = dict(
                    zip(
                        self.config.joint_names,
                        self.driver.get_all_positions(),
                        strict=True,
                    )
                )
                self._enter_estop_hold(present)
                if getattr(self.config, "abort_on_estop", False):
                    raise RuntimeError(
                        f"E-stop engaged ({self._estop.state.value}); policy inference aborted"
                    )
            elif not self._estop.engaged and self._estop_hold is not None:
                present = dict(
                    zip(
                        self.config.joint_names,
                        self.driver.get_all_positions(),
                        strict=True,
                    )
                )
                self._leave_estop_hold(present)
        self._ensure_staged()
        observation = super().get_observation()
        if getattr(self.config, "depth_policy_encoding", ""):
            for key in [name for name in observation if name.endswith("_depth")]:
                observation[key] = encode_depth_mm(observation[key])
        return observation

    @property
    def observation_features(self) -> dict[str, type | tuple]:
        features = dict(super().observation_features)
        if getattr(self.config, "depth_policy_encoding", ""):
            for key, shape in list(features.items()):
                if key.endswith("_depth") and isinstance(shape, tuple):
                    features[key] = (*shape[:-1], 3)
        return features

    def _ensure_staged(self) -> None:
        """First use lifts every deferred arm in the group, together."""
        if self._pending_stage is not None and not (
            self._estop is not None and self._estop.engaged
        ):
            recovery.arm_group.stage_pending()

    def _enter_estop_hold(self, present: dict[str, float]) -> None:
        """Snap the arm and every command anchor to its measured pose."""
        self._estop_hold = dict(present)
        arm_joints = self.config.joint_names[: self.GRIPPER]
        held_arm = {j: present[j] for j in arm_joints}
        self.driver.set_arm_modes(trossen_arm.Mode.position)
        self.driver.set_arm_positions(
            [held_arm[j] for j in arm_joints], 0.0, False
        )
        # Lift the pen off the work along its own axis. Only once staging has
        # seated the carriage: pressed at connect, it stays where it is.
        # (getattr: the hold must never raise — a raise here leaves the arm
        # un-frozen — and a partially built follower has no carriage state.)
        if getattr(self, "_carriage_target", None) is not None:
            self._set_carriage(self.config.carriage_retract_m, 0.15)
        self._contact_trip = False
        self._contact_n = 0
        self._cmd_target = held_arm
        self._filt_target = dict(held_arm)
        self._cmd_time = time.monotonic()
        self._scale_state = None
        self._watchdog = recovery.TrackingWatchdog()
        if hasattr(self, "_motion_watchdog"):
            self._motion_watchdog.reset(time.monotonic())
        # An earlier overforce retreat must not become the first target after
        # release. The E-stop's measured pose is the only valid new baseline.
        self._overforce_hold = None
        self._overforce_t = 0.0
        self._overforce_n = 0
        self._pose_history.clear()
        estop_state = self._estop.state.value if self._estop is not None else "engaged"
        logger.warning(
            "E-STOP engaged (%s): arm frozen, pen retracted, actions ignored",
            estop_state,
        )
        runlog_shim.event(
            "estop", state=estop_state, arm="follower"
        )

    def _leave_estop_hold(self, present: dict[str, float]) -> None:
        """Resume through freshly seeded filtering and slew state."""
        self._estop_hold = None
        arm_joints = self.config.joint_names[: self.GRIPPER]
        self._cmd_target = {j: present[j] for j in arm_joints}
        self._filt_target = dict(self._cmd_target)
        self._cmd_time = time.monotonic()
        self._scale_state = None
        self._watchdog = recovery.TrackingWatchdog()
        if hasattr(self, "_motion_watchdog"):
            self._motion_watchdog.reset(time.monotonic())
        self._overforce_hold = None
        self._overforce_t = 0.0
        self._overforce_n = 0
        self._pose_history.clear()
        if getattr(self, "_carriage_target", None) is not None:
            self._set_carriage(self.config.carriage_rest_m, self.config.carriage_goal_time_s)
        logger.warning("E-stop released: carriage back to rest, resuming commanded actions")
        runlog_shim.event("estop", state="released", arm="follower")

    def _hard_abort(
        self, present: dict[str, float], abort: MotionSafetyError
    ) -> None:
        """Freeze at the measured pose before propagating a safety failure."""
        arm_joints = self.config.joint_names[: self.GRIPPER]
        measured = {joint: present[joint] for joint in arm_joints}
        with contextlib.suppress(Exception):
            self.driver.set_arm_modes(trossen_arm.Mode.position)
            self.driver.set_arm_positions(
                [measured[joint] for joint in arm_joints], 0.0, False
            )
        with contextlib.suppress(Exception):
            if getattr(self, "_carriage_target", None) is not None:
                self._set_carriage(self.config.carriage_retract_m, 0.15)
        self._cmd_target = measured
        self._filt_target = dict(measured)
        self._cmd_time = time.monotonic()
        self._scale_state = None
        logger.error("MOTION SAFETY ABORT [%s]: %s", abort.code, abort)
        runlog_shim.event(
            "safety_abort",
            code=abort.code,
            msg=str(abort),
            metrics=abort.metrics,
        )

    def resume_after_abort(self) -> None:
        """Clear the safety hold so a paused recording can continue.

        A MotionSafetyError leaves the arm frozen at the measured pose
        (_hard_abort) with the watchdog history still full — resuming without
        this re-trips instantly. Drop the watchdog history and the slew
        anchors so the next send_action starts fresh from the measured pose;
        every safety limit stays armed.
        """
        self._motion_watchdog.reset()
        self._cmd_target = None
        self._filt_target = None
        self._cmd_time = None
        self._scale_state = None
        # Contact/overforce machinery restarts clean too: a trip carried
        # across the pause would ignore the leader forever, and the restage
        # that follows recaptures the rest baseline once settled.
        self._contact_trip = False
        self._contact_n = 0
        self._overforce_hold = None
        self._overforce_n = 0
        self._overforce_t = 0.0
        self._pose_history.clear()

    def _apply_motion_scale(
        self, request: dict[str, float], arm_joints
    ) -> dict[str, float]:
        """EXPERIMENTAL leader→follower motion scaling (arm joints only).

        Scales requested motion about the pose held when the scale vector
        last changed, so toggling scale mid-session never steps the target:
        goal = anchor_cmd + s · (request − anchor_req). At 1.0 everywhere
        (the default) this is a no-op and the anchors reset.
        """
        scale = [float(s) for s in self.config.motion_scale]
        if all(abs(s - 1.0) < 1e-9 for s in scale):
            self._scale_state = None
            return request
        state = self._scale_state
        if state is None or state["scale"] != scale:
            anchor_cmd = (
                dict(self._cmd_target)
                if self._cmd_target is not None
                else {j: request[j] for j in arm_joints}
            )
            state = {
                "scale": scale,
                "anchor_req": {j: request[j] for j in arm_joints},
                "anchor_cmd": anchor_cmd,
            }
            self._scale_state = state
        return {
            j: state["anchor_cmd"][j]
            + scale[i] * (request[j] - state["anchor_req"][j])
            for i, j in enumerate(arm_joints)
        }

    def disconnect(self, land: bool = True) -> None:
        """land=False: the arm was already brought down by a coordinated
        multi-arm landing (recovery.land_arms_together), so skip the motion
        and just release the hardware."""
        # The stock disconnect drives the arm (staged/sleep moves); never do
        # that with the e-stop latched — hold and wait for the twist-release.
        # Ctrl+C during the wait aborts disconnect (driver teardown idles).
        if self._estop is not None and self._estop.engaged:
            logger.warning(
                "disconnect requested with e-stop engaged (%s): holding until "
                "twist-release", self._estop.state.value,
            )
            while self._estop.engaged:
                time.sleep(0.05)
        # Shield the landing from Ctrl+C: a KeyboardInterrupt inside the
        # blocking staged/sleep moves below would abort them and leave the arm
        # frozen in position mode, holding its last target. The rollout
        # scripts already shield at the process level (il_client_shield.py);
        # this covers every other caller (lerobot-record, ad-hoc use). Only
        # possible from the main thread; the hardware e-stop is always live.
        prev_sigint = None
        with contextlib.suppress(ValueError):
            prev_sigint = signal.signal(
                signal.SIGINT,
                lambda *_: logger.warning(
                    "landing in progress — Ctrl+C ignored (arm idles in a few seconds)"
                ),
            )
            # SA_RESTART: the swallowed signal must not EINTR-abort the
            # driver's blocking socket reads (the SDK does not retry EINTR).
            signal.siginterrupt(signal.SIGINT, False)
        if land and self.config.coordinated_arms and recovery.arm_group.names():
            recovery.arm_group.land()  # lands the whole fleet, once
            land = False
        if not land:
            with contextlib.suppress(Exception):
                self.driver.set_all_modes(trossen_arm.Mode.idle)
            with contextlib.suppress(Exception):
                self.driver.cleanup()
            for cam in self.cameras.values():
                with contextlib.suppress(Exception):
                    cam.disconnect()
            self._teardown()
            if prev_sigint is not None:
                with contextlib.suppress(Exception):
                    signal.signal(signal.SIGINT, prev_sigint)
            return
        # All-position modes so the stock staged/sleep moves work. If the
        # controller is in a fault state (e.g. a firmware velocity trip mid-
        # rollout), driver calls raise — never let disconnect double-throw:
        # fall back to plain cleanup (the controller idles on client loss).
        emergency_landing_failed = False
        try:
            self.driver.set_all_modes(trossen_arm.Mode.position)
            self.driver.set_all_positions(
                self.driver.get_all_positions(),
                goal_time=0.5,
                blocking=True,
            )
            super().disconnect()
        except Exception:
            # Never leave the arm frozen holding its last position-mode
            # target. The landing runs over a FRESH driver session (this
            # one can no longer command, but the controller still accepts
            # connections), holds the carriage where it is, and verifies it
            # actually reached the sleep pose.
            logger.exception(
                "graceful disconnect failed (controller fault / dead session); "
                "attempting emergency landing"
            )
            with contextlib.suppress(Exception):
                self.driver.cleanup()
            emergency_landing_failed = not recovery.land_arm(
                self.config.ip_address,
                trossen_arm.StandardEndEffector.wxai_v0_follower,
                list(self.config.staged_positions),
                name="follower",
                gripper_index=self.GRIPPER,
                estop=self._estop,
            )
            for cam in self.cameras.values():
                with contextlib.suppress(Exception):
                    cam.disconnect()
        finally:
            if prev_sigint is not None:
                with contextlib.suppress(Exception):
                    signal.signal(signal.SIGINT, prev_sigint)
        self._teardown()
        if emergency_landing_failed:
            raise RuntimeError(
                "emergency landing failed; arm state is unknown and the run must fail"
            )

    def _flight_log_path(self) -> Path | None:
        """Where this session's flight CSV goes.

        Inside a run-logging session the CSV joins the rest of that run's
        evidence, so an agent finds it without knowing this class exists.
        Otherwise it keeps the historical flat layout — but named after the
        directory it lands in. The prefix used to be a hardcoded "rollout_"
        regardless of directory, so a tuning session wrote
        ~/tatbot-logs/tune/rollout_*.csv and the provenance became a lie the
        moment a file was copied anywhere.
        """
        run_dir = runlog_shim.run_dir()
        if run_dir is not None:
            return run_dir / f"flight-{self.config.id or 'follower'}.csv"
        directory = paths.flight_dir(self.config.flight_log_dir)
        if directory is None:
            return None
        return directory / time.strftime(f"{directory.name}_%Y%m%d_%H%M%S.csv")

    def _report_versions(self) -> None:
        """Record what actually drove the arm, from the connection we already
        hold — never a second one (the driver connection is exclusive).

        On 2026-08-21 a stale checkout served rollouts on trossen-arm 1.8.8,
        the pin whose own commit message records it wedging this controller
        twice inside a minute, and no artifact of those runs said so.
        """
        info: dict[str, Any] = {}
        # The shell-side collector runs under the system python3 and cannot see
        # this venv, so the versions that actually drove the arm have to be
        # recorded from in here. That gap is not academic: on 2026-08-21 the
        # rollouts ran on trossen-arm 1.8.8 and no artifact said so.
        packages: dict[str, str] = {}
        with contextlib.suppress(Exception):
            import importlib.metadata as md

            for name in ("trossen-arm", "lerobot", "lerobot_robot_trossen",
                         "lerobot_robot_tatbot", "torch", "numpy"):
                with contextlib.suppress(Exception):
                    packages[name] = md.version(name)
            info["trossen_arm"] = packages.get("trossen-arm")
        for attr in ("get_firmware_version", "get_controller_version"):
            fn = getattr(self.driver, attr, None)
            if callable(fn):
                with contextlib.suppress(Exception):
                    info[attr.removeprefix("get_")] = str(fn())
        if info:
            logger.info(f"{self} versions: {info}")
            runlog_shim.event("hardware", role="follower", ip=self.config.ip_address, **info)
            runlog_shim.update(
                hardware={"arms": [dict(role="follower", ip=self.config.ip_address, **info)]},
                versions={"python_packages": packages,
                          "venv": sys.prefix},
            )

    def _teardown(self) -> None:
        """Release everything that is not the arm itself (safe to call twice)."""
        recovery.arm_group.unregister("follower")
        with contextlib.suppress(Exception):
            warn_throttle.remove(getattr(self, "_clamp_throttle", None))
            self._clamp_throttle = None
        if self._flight_log is not None:
            with contextlib.suppress(Exception):
                self._flight_log.flush()
                os.fsync(self._flight_log.fileno())
            with contextlib.suppress(Exception):
                self._flight_log.close()
            self._flight_log = None
            self._flight_writer = None
        if self._estop is not None:
            release_estop(self._estop)
            self._estop = None
        self._estop_hold = None
        if self._tuning_server is not None:
            self._tuning_server.unregister("follower")
            self._tuning_server = None
            self._tuning = None
