// GENERATED by scripts/gen_motion_constants.py from config/motion_constants.json.
// Do not edit: change the JSON, rerun the generator, rebuild.
#pragma once
#include <array>

namespace tatbot::motion_constants
{
inline constexpr char SHA[] = "c36d529c2b43";

inline constexpr double PERIOD_S = 0.0025;
inline constexpr double CARRIAGE_IK_BIAS_M = 0.002;
inline constexpr double CARRIAGE_IK_MIN_M = 0.0005;
inline constexpr double CARRIAGE_IK_MAX_M = 0.0035;
inline constexpr double CARRIAGE_IK_PEN_UP_MIN_M = -0.006;
inline constexpr double CARRIAGE_IK_PEN_UP_MAX_M = 0.034;
inline constexpr double PLANNER_JOINT_LIMIT_MARGIN_RAD = 0.03333333333333333;
inline constexpr double PLANNER_MAX_JOINT_VELOCITY_RAD_S = 0.375;
inline constexpr double PLANNER_MAX_JOINT_VELOCITY_PEN_UP_RAD_S = 1.0;
inline constexpr double PLANNER_MAX_MODEL_ERROR_M = 0.00015000000000000001;
inline constexpr double PLANNER_MAX_MODEL_ERROR_PEN_UP_M = 0.0015;
inline constexpr double PLANNER_MAX_MODEL_ERROR_DRAW_M = 0.0015;
inline constexpr double PLANNER_MAX_ORIENTATION_ERROR_RAD = 0.005;
inline constexpr double PLANNER_DLS_DAMPING = 0.02;
inline constexpr double PLANNER_POSITION_ERROR_GAIN_S = 4.0;
inline constexpr double PLANNER_ORIENTATION_ERROR_GAIN_S = 2.0;
inline constexpr double PLANNER_CARRIAGE_DLS_WEIGHT = 2.0;
inline constexpr double PLANNER_CARRIAGE_CENTER_GAIN_S = 2.0;
inline constexpr double PLANNER_MAX_CARRIAGE_VELOCITY_M_S = 0.001;
inline constexpr double PLANNER_MAX_CARRIAGE_ACCELERATION_M_S2 = 0.02;
inline constexpr int PLANNER_MAX_TICKS = 250000;
inline constexpr double PATH_LEAN_BUDGET_DEG = 30.0;
inline constexpr double PATH_LEAN_DEADBAND_DEG = 12.0;
inline constexpr double PATH_DIP_TRAVEL_SPEED_M_S = 0.08;
inline constexpr std::array<double, 6> PATH_DIP_TRAVEL_BACKOFF_M_S{0.08, 0.06, 0.04, 0.025, 0.015, 0.01};
inline constexpr double PATH_DIP_DESCENT_SPEED_M_S = 0.01;
inline constexpr int ORBIT_POSES = 3;
inline constexpr double ORBIT_SPEED_MM_S = 100.0;
inline constexpr double ORBIT_NO_SCAN_LIFT_MM = 10.0;
inline constexpr double ORBIT_CAPTURE_SETTLED_RAD_S = 0.075;
inline constexpr double ORBIT_CAPTURE_SETTLED_S = 0.15;
inline constexpr double ORBIT_CAPTURE_SETTLE_MAX_S = 4.5;
inline constexpr double AUDIO_SERVO_RATE_M_S = 0.0005;
inline constexpr double AUDIO_SERVO_UP_M = 0.004;
inline constexpr double AUDIO_SERVO_STALE_S = 1.0;
inline constexpr double AUDIO_SERVO_STALL_S = 5.0;
inline constexpr double TOUCHOFF_FAST_M_S = 0.01;
inline constexpr double TOUCHOFF_SLOW_M_S = 0.0005;
inline constexpr double TOUCHOFF_SLOW_ABOVE_M = 0.004;
inline constexpr double TOUCHOFF_BELOW_M = 0.003;
inline constexpr double TOUCHOFF_LAG_M = 0.0008;
inline constexpr double TOUCHOFF_LAG_ARM_S = 0.5;
inline constexpr double TOUCHOFF_LAG_HOLD_S = 0.15;
inline constexpr double TOUCHOFF_EFFORT_STOP_N = 12.0;
inline constexpr double TOUCHOFF_EFFORT_HOLD_S = 0.25;
inline constexpr double TOUCHOFF_COVER_M = 0.025;
inline constexpr double TOUCHOFF_COVER_MAX_M = 0.04;
inline constexpr double TOUCHOFF_PRIOR_TILT_DEG = 8.0;
inline constexpr double TOUCHOFF_WIGGLE_M = 0.00075;
inline constexpr double TOUCHOFF_WIGGLE_HZ = 0.5;
inline constexpr double TOUCHOFF_RETURN_M_S = 0.015;
inline constexpr double TOUCHOFF_HOVER_WAIT_S = 1.0;
inline constexpr double TOUCHOFF_HOVER_TIMEOUT_S = 10.0;
inline constexpr double TOUCHOFF_SETTLE_S = 0.5;
inline constexpr double AUDIO_RULE_RMS_DROP_DB = 10.0;
inline constexpr double AUDIO_RULE_RMS_HYST_DB = 3.0;
inline constexpr int AUDIO_RULE_LATCH_ROWS = 3;
inline constexpr double DESIGN_RADIUS_TOLERANCE_FRACTION = 0.25;
inline constexpr double REGISTRATION_RESCAN_MAX_TRANSLATION_M = 0.008;
inline constexpr double REGISTRATION_RESCAN_MAX_ROTATION_RAD = 0.1;
inline constexpr double REGISTRATION_RESCAN_MAX_RADIUS_DELTA_M = 0.005;
inline constexpr double REGISTRATION_CAMERA_MAX_DISAGREEMENT_M = 0.03;

}  // namespace tatbot::motion_constants
