path: "~/tatbot/assets/urdf/tatbot.urdf"
ee_link_names:
  - "left/tattoo_needle"
  - "right/tattoo_needle"
tag_link_names:
  - "tag6"
  - "tag7"
  - "tag9"
  - "tag10"
  - "tag11"
cam_link_names:
  - "realsense1_color_optical_frame"
  - "realsense2_color_optical_frame"
  - "camera1_optical_frame"
  - "camera2_optical_frame"
  - "camera3_optical_frame"
  - "camera4_optical_frame"
  - "camera5_optical_frame"
ink_link_names:
  - "inkcap_large"
  - "inkcap_small_1"
  - "inkcap_small_2"
  - "inkcap_small_3"
  - "inkcap_medium_1"
  - "inkcap_medium_2"
root_link_name: "root"
skin_link_name: "skin"
