path: "~/tatbot/urdf/tatbot.urdf"
ee_link_names:
  - "left/tattoo_needle"
  - "right/tattoo_needle"
tag_link_names:
  - "tag0"
cam_link_names:
  - "left/realsense_depth_optical_frame"
  - "right/realsense_depth_optical_frame"
  - "camera1_optical_frame"
  - "camera2_optical_frame"
  - "camera3_optical_frame"
  - "camera4_optical_frame"
  - "camera5_optical_frame"
ink_link_names:
  - "inkcap_left_large"
  - "inkcap_left_small_0"
  - "inkcap_left_small_1"
  - "inkcap_left_medium_0"
  - "inkcap_left_medium_1"
  - "inkcap_right_large"
  - "inkcap_right_small_0"
  - "inkcap_right_small_1"
  - "inkcap_right_medium_0"
  - "inkcap_right_medium_1"
calibrator_link_name: "palette_calibrator"
lasercross_link_name: "lasercross"
root_link_name: "root"
