name: "align"
arms_config_name: "bimanual"
cams_config_name: "all"
urdf_config_name: "default"
skin_config_name: "fakeskin"
tags_config_name: "default"
sleep_pos_l_name: "left/sleep"
sleep_pos_r_name: "right/sleep"
ready_pos_l_name: "left/retracted"
ready_pos_r_name: "right/retracted"
inkready_pos_l_name: "left/inkready"
inkready_pos_r_name: "right/inkready"
inks_config_name: "full"
pen_names_l:
  - nighthawk_black
  - snow_white
  - fuchsia
  - golden_yellow
  - bright_orange
  - bright_red
  - lime_green
  - true_blue
pen_names_r:
  - nighthawk_black
  - snow_white
  - fuchsia
  - golden_yellow
  - bright_orange
  - bright_red
  - lime_green
  - true_blue
pens_config_path: "~/tatbot/config/drawingbotv3/pens/full.json"
stroke_length: 32
ee_rot_l:
  wxyz: [0.5, 0.5, 0.5, -0.5]
ee_rot_r:
  wxyz: [0.5, -0.5, 0.5, 0.5]
inkdip_hover_offset:
  xyz: [0.0, 0.0, 0.02] # 2cm above inkcap
needle_hover_offset:
  xyz: [0.0, 0.0, 0.02] # 2cm above design
needle_offset_l:
  xyz: [0.0, 0.0, 0.0]
needle_offset_r:
  xyz: [0.0, 0.0, 0.0]
design_dir_path: null # align scene does not have a design