name: "align"
arms_config_name: "bimanual"
cams_config_name: "fast"
urdf_config_name: "default"
skin_config_name: "fakeskin"
tags_config_name: "default"
sleep_pos_l_name: "left/sleep"
sleep_pos_r_name: "right/sleep"
ready_pos_l_name: "left/ready"
ready_pos_r_name: "right/ready"
inkready_pos_l_name: "left/inkready"
inkready_pos_r_name: "right/inkready"
inks_config_name: "full"
pen_names_l:
  - nighthawk_black
  - snow_white
  - fuchsia
  - golden_yellow
  - bright_orange
  - bright_red
  - lime_green
  - true_blue
pen_names_r:
  - nighthawk_black
  - snow_white
  - fuchsia
  - golden_yellow
  - bright_orange
  - bright_red
  - lime_green
  - true_blue
pens_config_path: "~/tatbot/config/dbv3/pens/full.json"
stroke_length: 32
ee_rot_l:
  wxyz: [0.5, 0.5, 0.5, -0.5]
ee_rot_r:
  wxyz: [0.5, -0.5, 0.5, 0.5]
hover_offset:
  xyz: [0.0, 0.0, 0.02] # 2cm for alignment
ee_offset_l:
  xyz: [0.0, 0.0, 0.0]
ee_offset_r:
  xyz: [0.0, 0.0, 0.0]
offset_range: [-0.01, 0.01]
offset_num: 3
design_dir_path: null # align scene does not have a design