name: "default"
arms_config_name: "bimanual"
cams_config_name: "all"
zone_config_name: "metaltray"
urdf_config_name: "default"
skin_config_name: "fakeskin"
inks_config_name: "black"
tags_config_name: "default"
sleep_pos_l_name: "left/sleep"
sleep_pos_r_name: "right/sleep"
ready_pos_l_name: "left/retracted"
ready_pos_r_name: "right/retracted"
inkready_pos_l_name: "left/inkready"
inkready_pos_r_name: "right/inkready"