name: "default"
arms_config_name: "bimanual"
cams_config_name: "all"
zone_config_name: "metaltray"
urdf_config_name: "default"
skin_config_name: "fakeskin"
inks_config_name: "blacknwhite"
tags_config_name: "default"
home_pos_l_name: "left/rest"
home_pos_r_name: "right/rest"