import { chromium } from "playwright";
import { mkdirSync } from "node:fs";
const out = new URL("./out/", import.meta.url).pathname;
mkdirSync(out, { recursive: true });
const browser = await chromium.launch({ channel: "chrome", headless: true, args: ["--ignore-gpu-blocklist"] });
const page = await (await browser.newContext({ viewport: { width: 900, height: 1100 } })).newPage();
await page.goto("http://127.0.0.1:4181/");
await page.waitForFunction(() => window.__inkmap?.getState().body && window.__inkmap?.getState().atlas, null, { timeout: 60_000 });
await page.fill(".sentence input", "a star on the left elbow");
await page.click(".sentence button.primary");
await page.waitForFunction(() => window.__inkmap.getState().placements.length === 1, null, { timeout: 10_000 });
await page.evaluate(() => { const s = window.__inkmap.getState(); s.setPending(null); });
await page.fill(".sentence input", "a heart on the left knee");
await page.click(".sentence button.primary");
await page.waitForFunction(() => window.__inkmap.getState().placements.length === 2, null, { timeout: 10_000 });
await page.waitForTimeout(1200);
await page.screenshot({ path: `${out}/elbow-knee.png`, clip: { x: 320, y: 0, width: 580, height: 1100 } });
await browser.close();
console.log(await page.evaluate ? "done" : "done");
