name: "default"
arms_config_name: "default"
cams_config_name: "default"
urdf_config_name: "default"
skin_config_name: "default"
inks_config_name: "default"
tags_config_name: "default"
sleep_pos_l_name: "left/sleep"
sleep_pos_r_name: "right/sleep"
ready_pos_l_name: "left/ready"
ready_pos_r_name: "right/ready"
pen_names_l:
  - true_blue
  - snow_white
  - fuchsia
  - golden_yellow
  - bright_orange
  - nighthawk_black
  - lime_green
pen_names_r:
  - bright_red
  - snow_white
  - fuchsia
  - golden_yellow
  - bright_orange
  - nighthawk_black
  - lime_green
pens_config_path: "~/tatbot/config/dbv3/pens/full.json"
stroke_length: 80
design_dir_path: "~/tatbot/nfs/designs/default"
