apriltag:
  ros__parameters:
    family: '16h5'
    size: 0.04
    standalone_tags:
      # - id: 2
      #   size: 0.04
      - id: 3
        size: 0.04
      - id: 4
        size: 0.04
      - id: 5
        size: 0.04