cameras:
  camera1:
    ip: "192.168.1.91"
    username: "admin"  # Default Amcrest username
    password: "${CAMERA_1_PASSWORD}"  # Will be loaded from environment variable
    rtsp_port: 554
    stream_path: "/cam/realmonitor?channel=1&subtype=0"  # Main stream
    resolution: [2592, 1944]  # 5MP
    fps: 1
  camera2:
    ip: "192.168.1.92"
    username: "admin"
    password: "${CAMERA_2_PASSWORD}"
    rtsp_port: 554
    stream_path: "/cam/realmonitor?channel=1&subtype=0"
    resolution: [2592, 1944]
    fps: 1
  camera3:
    ip: "192.168.1.93"
    username: "admin"
    password: "${CAMERA_3_PASSWORD}"
    rtsp_port: 554
    stream_path: "/cam/realmonitor?channel=1&subtype=0"
    resolution: [2592, 1944]
    fps: 1
  camera4:
    ip: "192.168.1.94"
    username: "admin"
    password: "${CAMERA_4_PASSWORD}"
    rtsp_port: 554
    stream_path: "/cam/realmonitor?channel=1&subtype=0"
    resolution: [2592, 1944]
    fps: 1
  camera5:
    ip: "192.168.1.95"
    username: "admin"
    password: "${CAMERA_5_PASSWORD}"
    rtsp_port: 554
    stream_path: "/cam/realmonitor?channel=1&subtype=0"
    resolution: [2592, 1944]
    fps: 1

output_dir: "output/cameras"  # Directory to save captured images
image_format: "jpg"  # Output image format