ojo:
  device_name: "ubuntu"
  ip: "192.168.1.96"
  username: "ojo"
  # MAC: "90:E8:68:BC:80:79" # wifi
  MAC: "48:B0:2D:A5:08:C6" # ethernet

trossen-ai:
  device_name: "trossen-ai-pc"
  ip: "192.168.1.97"
  username: "trossen-ai"
  MAC: "48:21:0B:6B:DA:9C"

rpi1:
  device_name: "rpi1"
  ip: "192.168.1.98"
  username: "rpi1"
  MAC: "2C:CF:67:25:58:7C"

rpi2:
  device_name: "rpi2"
  ip: "192.168.1.99"
  username: "rpi2"
  MAC: "2C:CF:67:25:9A:7C"