factory_reset_flag: false
ip_method: manual
manual_ip: 192.168.1.2
dns: 8.8.8.8
gateway: 192.168.1.1
subnet: 255.255.255.0
joint_characteristics:
  - effort_correction: 1.5005325078964233
    friction_transition_velocity: 0
    friction_constant_term: -0.009999999776482582
    friction_coulomb_coef: 0.23910273611545563
    friction_viscous_coef: 0.25152266025543213
  - effort_correction: 1.2989336252212524
    friction_transition_velocity: 0
    friction_constant_term: 0.25
    friction_coulomb_coef: 0.12398207932710648
    friction_viscous_coef: -0.004761803895235062
  - effort_correction: 1.3286081552505493
    friction_transition_velocity: 0
    friction_constant_term: 0.2199999988079071
    friction_coulomb_coef: 0.11595069617033005
    friction_viscous_coef: -0.1738549917936325
  - effort_correction: 1.2467381954193115
    friction_transition_velocity: 0
    friction_constant_term: -0.07000000029802322
    friction_coulomb_coef: 0.02338099665939808
    friction_viscous_coef: 0.024639787152409554
  - effort_correction: 1.1713294982910156
    friction_transition_velocity: 0
    friction_constant_term: -0.009999999776482582
    friction_coulomb_coef: 0.011764136143028736
    friction_viscous_coef: 0.027401674538850784
  - effort_correction: 1.2000000476837158
    friction_transition_velocity: 0
    friction_constant_term: -0.009999999776482582
    friction_coulomb_coef: 0
    friction_viscous_coef: 0.016608310863375664
  - effort_correction: 1.2000000476837158
    friction_transition_velocity: 0
    friction_constant_term: 11.569999694824219
    friction_coulomb_coef: 0
    friction_viscous_coef: 63.876773834228516
modes:
  - idle
  - idle
  - idle
  - idle
  - idle
  - idle
  - idle
end_effector:
  palm:
    mass: 0.642300009727478
    inertia:
      - 0.0010848400415852666
      - 6.299999881775875e-07
      - -4.180000178166665e-05
      - 6.299999881775875e-07
      - 0.0007517000194638968
      - -1.5580000763293356e-05
      - -4.180000178166665e-05
      - -1.5580000763293356e-05
      - 0.0011099399998784065
    origin_xyz:
      - 0.046995919197797775
      - 0.0004593599878717214
      - 0.008277719840407372
    origin_rpy:
      - 0
      - 0
      - 0
  finger_left:
    mass: 0.059450000524520874
    inertia:
      - 1.8750000890577212e-05
      - 3.0900000638212077e-06
      - -1.4900000451234519e-06
      - 3.0900000638212077e-06
      - 2.6140000045415945e-05
      - -1.2399999604895129e-06
      - -1.4900000451234519e-06
      - -1.2399999604895129e-06
      - 2.995000068040099e-05
    origin_xyz:
      - 0.0016901600174605846
      - -0.00592795992270112
      - -0.003657009918242693
    origin_rpy:
      - 0
      - 0
      - 0
  finger_right:
    mass: 0.059450000524520874
    inertia:
      - 1.9299999621580355e-05
      - -3.0900000638212077e-06
      - 3.5900000057154102e-06
      - -3.0900000638212077e-06
      - 2.6699999580159783e-05
      - -6.399999961104186e-07
      - 3.5900000057154102e-06
      - -6.399999961104186e-07
      - 2.995000068040099e-05
    origin_xyz:
      - 0.0016901500057429075
      - 0.005927930120378733
      - 0.002018179977312684
    origin_rpy:
      - 0
      - 0
      - 0
  offset_finger_left: 0.022700000554323196
  offset_finger_right: -0.022700000554323196
  pitch_circle_radius: 0.008750000037252903
  t_flange_tool:
    - 0.156062
    - 0
    - 0
    - 0
    - 0
    - 0
joint_limits:
  - position_min: -3.1415927410125732
    position_max: 3.1415927410125732
    position_tolerance: 0.20000000298023224
    velocity_max: 6.2831854820251465
    velocity_tolerance: 0
    effort_max: 27
    effort_tolerance: 5.400000095367432
  - position_min: 0
    position_max: 3.1415927410125732
    position_tolerance: 0.20000000298023224
    velocity_max: 6.2831854820251465
    velocity_tolerance: 0
    effort_max: 27
    effort_tolerance: 5.400000095367432
  - position_min: 0
    position_max: 2.356194496154785
    position_tolerance: 0.20000000298023224
    velocity_max: 6.2831854820251465
    velocity_tolerance: 0
    effort_max: 27
    effort_tolerance: 5.400000095367432
  - position_min: -1.5707963705062866
    position_max: 1.5707963705062866
    position_tolerance: 0.4000000059604645
    velocity_max: 9.42477798461914
    velocity_tolerance: 0
    effort_max: 7
    effort_tolerance: 1.399999976158142
  - position_min: -1.5707963705062866
    position_max: 1.5707963705062866
    position_tolerance: 0.4000000059604645
    velocity_max: 9.42477798461914
    velocity_tolerance: 0
    effort_max: 7
    effort_tolerance: 1.399999976158142
  - position_min: -3.1415927410125732
    position_max: 3.1415927410125732
    position_tolerance: 0.4000000059604645
    velocity_max: 9.42477798461914
    velocity_tolerance: 0
    effort_max: 7
    effort_tolerance: 1.399999976158142
  - position_min: 0
    position_max: 0.03999999910593033
    position_tolerance: 0.004000000189989805
    velocity_max: 0.25
    velocity_tolerance: 0
    effort_max: 100
    effort_tolerance: 300
motor_parameters:
  - idle:
      position:
        kp: 0
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 8
        ki: 0.03999999910593033
        kd: 0
        imax: 9
    position:
      position:
        kp: 120
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 8
        ki: 0.004000000189989805
        kd: 0
        imax: 9
    velocity:
      position:
        kp: 120
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 8
        ki: 0
        kd: 0
        imax: 0
    external_effort:
      position:
        kp: 120
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 8
        ki: 0
        kd: 0
        imax: 0
    effort:
      position:
        kp: 120
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 8
        ki: 0
        kd: 0
        imax: 0
  - idle:
      position:
        kp: 0
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 8
        ki: 0.03999999910593033
        kd: 0
        imax: 27
    position:
      position:
        kp: 120
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 8
        ki: 0.004000000189989805
        kd: 0
        imax: 9
    velocity:
      position:
        kp: 120
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 8
        ki: 0
        kd: 0
        imax: 0
    external_effort:
      position:
        kp: 120
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 8
        ki: 0
        kd: 0
        imax: 0
    effort:
      position:
        kp: 120
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 8
        ki: 0
        kd: 0
        imax: 0
  - idle:
      position:
        kp: 0
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 8
        ki: 0.03999999910593033
        kd: 0
        imax: 9
    position:
      position:
        kp: 120
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 8
        ki: 0.004000000189989805
        kd: 0
        imax: 9
    velocity:
      position:
        kp: 120
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 8
        ki: 0
        kd: 0
        imax: 0
    external_effort:
      position:
        kp: 120
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 8
        ki: 0
        kd: 0
        imax: 0
    effort:
      position:
        kp: 120
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 8
        ki: 0
        kd: 0
        imax: 0
  - idle:
      position:
        kp: 0
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 1
        ki: 0.009999999776482582
        kd: 0
        imax: 3
    position:
      position:
        kp: 80
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 1
        ki: 0.0010000000474974513
        kd: 0
        imax: 3
    velocity:
      position:
        kp: 80
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 1
        ki: 0
        kd: 0
        imax: 0
    external_effort:
      position:
        kp: 80
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 1
        ki: 0
        kd: 0
        imax: 0
    effort:
      position:
        kp: 80
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 1
        ki: 0
        kd: 0
        imax: 0
  - idle:
      position:
        kp: 0
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 1
        ki: 0.009999999776482582
        kd: 0
        imax: 3
    position:
      position:
        kp: 40
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 1
        ki: 0.0010000000474974513
        kd: 0
        imax: 3
    velocity:
      position:
        kp: 40
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 1
        ki: 0
        kd: 0
        imax: 0
    external_effort:
      position:
        kp: 40
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 1
        ki: 0
        kd: 0
        imax: 0
    effort:
      position:
        kp: 40
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 1
        ki: 0
        kd: 0
        imax: 0
  - idle:
      position:
        kp: 0
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 1
        ki: 0.009999999776482582
        kd: 0
        imax: 3
    position:
      position:
        kp: 40
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 1
        ki: 0.0010000000474974513
        kd: 0
        imax: 3
    velocity:
      position:
        kp: 40
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 1
        ki: 0
        kd: 0
        imax: 0
    external_effort:
      position:
        kp: 40
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 1
        ki: 0
        kd: 0
        imax: 0
    effort:
      position:
        kp: 40
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 1
        ki: 0
        kd: 0
        imax: 0
  - idle:
      position:
        kp: 0
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 0.05000000074505806
        ki: 0.0005000000237487257
        kd: 0
        imax: 3
    position:
      position:
        kp: 20
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 1
        ki: 0.0010000000474974513
        kd: 0
        imax: 3
    velocity:
      position:
        kp: 20
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 1
        ki: 0
        kd: 0
        imax: 0
    external_effort:
      position:
        kp: 20
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 1
        ki: 0
        kd: 0
        imax: 0
    effort:
      position:
        kp: 20
        ki: 0
        kd: 0
        imax: 0
      velocity:
        kp: 1
        ki: 0
        kd: 0
        imax: 0
algorithm_parameter:
  singularity_threshold: 0.01
