name: default
left_arm_pen_names:
  - nighthawk_black
  # - true_blue
right_arm_pen_names:
  - nighthawk_black
  # - bright_red
# # A7 size
# image_width_m: 0.074
# image_height_m: 0.105
image_width_m: 0.1
image_height_m: 0.07
image_width_px: 1181
image_height_px: 826
ik_batch_size: 256
stroke_length: 64
ee_rot_l:
  wxyz: [0.5, 0.5, 0.5, -0.5]
ee_rot_r:
  wxyz: [0.5, -0.5, 0.5, 0.5]
inkdip_hover_offset:
  xyz: [0.0, 0.0, 0.003]
needle_hover_offset:
  xyz: [0.0, 0.0, 0.008]
needle_offset_l:
  xyz: [0.0, 0.0, -0.0044]
needle_offset_r:
  xyz: [0.0, 0.0, -0.0038]