name: default
left_arm_pen_names:
  - true_black
right_arm_pen_names:
  - bright_red
# # A7 size
# image_width_m: 0.074
# image_height_m: 0.105
image_width_m: 0.05
image_height_m: 0.05
image_width_px: 590
image_height_px: 590
ik_batch_size: 1024
path_length: 128
path_dt_fast: 0.08
path_dt_slow: 2.0
ee_wxyz_l:
  wxyz: [0.5, 0.5, 0.5, -0.5]
ee_wxyz_r:
  wxyz: [0.5, -0.5, 0.5, 0.5]
inkdip_hover_offset:
  xyz: [0.0, 0.0, 0.003]
needle_hover_offset:
  xyz: [0.0, 0.0, 0.008]
needle_offset_l:
  xyz: [0.0, 0.0, -0.02]
needle_offset_r:
  xyz: [0.0, 0.0, -0.02]