ipcameras:
  - name: "camera1"
    width: 1920
    height: 1080
    fps: 5
    urdf_link_name: "camera1_optical_frame"
    ip: "192.168.1.91"
    username: "admin"
    password: "CAMERA_1_PASSWORD"
    rtsp_port: 554
    intrinsics:
      fov: 1.937
      fov_depth: null
      aspect: 1.77
      fx: 664.0
      fy: 976.5
      ppx: 960.0
      ppy: 540.0
    extrinsics:
      pos:
        xyz: [0.0, 0.0, 0.0]
      rot:
        wxyz: [1.0, 0.0, 0.0, 0.0]
  - name: "camera2"
    width: 1920
    height: 1080
    fps: 5
    urdf_link_name: "camera2_optical_frame"
    ip: "192.168.1.92"
    username: "admin"
    password: "CAMERA_2_PASSWORD"
    rtsp_port: 554
    intrinsics:
      fov: 1.937
      fov_depth: null
      aspect: 1.77
      fx: 664.0
      fy: 976.5
      ppx: 960.0
      ppy: 540.0
    extrinsics:
      pos:
        xyz: [0.0, 0.0, 0.0]
      rot:
        wxyz: [1.0, 0.0, 0.0, 0.0]
  - name: "camera3"
    width: 1920
    height: 1080
    fps: 5
    urdf_link_name: "camera3_optical_frame"
    ip: "192.168.1.93"
    username: "admin"
    password: "CAMERA_3_PASSWORD"
    rtsp_port: 554
    intrinsics:
      fov: 1.937
      fov_depth: null
      aspect: 1.77
      fx: 664.0
      fy: 976.5
      ppx: 960.0
      ppy: 540.0
    extrinsics:
      pos:
        xyz: [0.0, 0.0, 0.0]
      rot:
        wxyz: [1.0, 0.0, 0.0, 0.0]
  - name: "camera4"
    width: 1920
    height: 1080
    fps: 5
    urdf_link_name: "camera4_optical_frame"
    ip: "192.168.1.94"
    username: "admin"
    password: "CAMERA_4_PASSWORD"
    rtsp_port: 554
    intrinsics:
      fov: 1.937
      fov_depth: null
      aspect: 1.77
      fx: 664.0
      fy: 976.5
      ppx: 960.0
      ppy: 540.0
    extrinsics:
      pos:
        xyz: [0.0, 0.0, 0.0]
      rot:
        wxyz: [1.0, 0.0, 0.0, 0.0]
  - name: "camera5"
    width: 1920
    height: 1080
    fps: 5
    urdf_link_name: "camera5_optical_frame"
    ip: "192.168.1.95"
    username: "admin"
    password: "CAMERA_5_PASSWORD"
    rtsp_port: 554
    intrinsics:
      fov: 1.937
      fov_depth: null
      aspect: 1.77
      fx: 664.0
      fy: 976.5
      ppx: 960.0
      ppy: 540.0
    extrinsics:
      pos:
        xyz: [0.0, 0.0, 0.0]
      rot:
        wxyz: [1.0, 0.0, 0.0, 0.0]
realsenses:
  - name: "realsense1"
    width: 640
    height: 480
    fps: 30
    serial_number: "230422273017"
    urdf_link_name: "left/realsense_depth_optical_frame"
    intrinsics:
      fov: 1.544
      fov_depth: 1.571
      aspect: 1.33
      fx: 327.5
      fy: 433.54
      ppx: 325.1
      ppy: 238.7
    extrinsics:
      pos:
        xyz: [0.0, 0.0, 0.0]
      rot:
        wxyz: [1.0, 0.0, 0.0, 0.0]
  - name: "realsense2"
    width: 640
    height: 480
    fps: 30
    serial_number: "218622278376"
    urdf_link_name: "right/realsense_depth_optical_frame"
    intrinsics:
      fov: 1.544
      fov_depth: 1.571
      aspect: 1.33
      fx: 328.2
      fy: 434.33
      ppx: 316.3
      ppy: 237.81
    extrinsics:
      pos:
        xyz: [0.0, 0.0, 0.0]
      rot:
        wxyz: [1.0, 0.0, 0.0, 0.0]
