ipcameras:
  - name: "camera1"
    width: 1920
    height: 1080
    fps: 5
    ip: "192.168.1.91"
    username: "admin"
    password: "CAMERA_1_PASSWORD"
    rtsp_port: 554
    intrinsics:
      fov: 1.57
      fov_depth: null
      aspect: 1.77
      fx: 1000.0
      fy: 1000.0
      ppx: 1480.0
      ppy: 834.0
    extrinsics:
      pos:
        xyz: [0.0, 0.0, 0.0]
      rot:
        wxyz: [1.0, 0.0, 0.0, 0.0]
  - name: "camera2"
    width: 1920
    height: 1080
    fps: 5
    ip: "192.168.1.92"
    username: "admin"
    password: "CAMERA_2_PASSWORD"
    rtsp_port: 554
    intrinsics:
      fov: 1.57
      fov_depth: null
      aspect: 1.77
      fx: 1000.0
      fy: 1000.0
      ppx: 1480.0
      ppy: 834.0
    extrinsics:
      pos:
        xyz: [0.0, 0.0, 0.0]
      rot:
        wxyz: [1.0, 0.0, 0.0, 0.0]
  - name: "camera3"
    width: 1920
    height: 1080
    fps: 5
    ip: "192.168.1.93"
    username: "admin"
    password: "CAMERA_3_PASSWORD"
    rtsp_port: 554
    intrinsics:
      fov: 1.57
      fov_depth: null
      aspect: 1.77
      fx: 1000.0
      fy: 1000.0
      ppx: 1480.0
      ppy: 834.0
    extrinsics:
      pos:
        xyz: [0.0, 0.0, 0.0]
      rot:
        wxyz: [1.0, 0.0, 0.0, 0.0]
  - name: "camera4"
    width: 1920
    height: 1080
    fps: 5
    ip: "192.168.1.94"
    username: "admin"
    password: "CAMERA_4_PASSWORD"
    rtsp_port: 554
    intrinsics:
      fov: 1.57
      fov_depth: null
      aspect: 1.77
      fx: 1000.0
      fy: 1000.0
      ppx: 1480.0
      ppy: 834.0
    extrinsics:
      pos:
        xyz: [0.0, 0.0, 0.0]
      rot:
        wxyz: [1.0, 0.0, 0.0, 0.0]
  - name: "camera5"
    width: 1920
    height: 1080
    fps: 5
    ip: "192.168.1.95"
    username: "admin"
    password: "CAMERA_5_PASSWORD"
    rtsp_port: 554
    intrinsics:
      fov: 1.57
      fov_depth: null
      aspect: 1.77
      fx: 1000.0
      fy: 1000.0
      ppx: 1480.0
      ppy: 834.0
    extrinsics:
      pos:
        xyz: [0.0, 0.0, 0.0]
      rot:
        wxyz: [1.0, 0.0, 0.0, 0.0]
realsenses:
  - name: "realsense1"
    width: 640
    height: 480
    fps: 30
    serial_number: "218622278376"
    intrinsics:
      # Color FOV (degrees): H=69.4, V=42.5, D=77
      # Depth FOV (degrees): H=86, V=57, D=94
      fov: 1.211 # 69.4 deg in radians
      fov_depth: 1.501 # 86 deg in radians
      aspect: 1.33
      fx: 434.0506591796875
      fy: 433.5442810058594
      ppx: 430.9583435058594
      ppy: 238.70144653320312
    extrinsics:
      pos:
        xyz: [0.0, 0.0, 0.0]
      rot:
        wxyz: [1.0, 0.0, 0.0, 0.0]
  - name: "realsense2"
    width: 640
    height: 480
    fps: 30
    serial_number: "230422273017"
    intrinsics:
      # Color FOV (degrees): H=69.4, V=42.5, D=77
      # Depth FOV (degrees): H=86, V=57, D=94
      fov: 1.211 # 69.4 deg in radians
      fov_depth: 1.501 # 86 deg in radians
      aspect: 1.33
      fx: 434.95263671875
      fy: 434.330078125
      ppx: 419.0846862792969
      ppy: 237.813232421875
    extrinsics:
      pos:
        xyz: [0.0, 0.0, 0.0]
      rot:
        wxyz: [1.0, 0.0, 0.0, 0.0]