#!/usr/bin/env python3
"""Render the motion constants C++ header from config/motion_constants.json.

    scripts/gen_motion_constants.py           # write the header
    scripts/gen_motion_constants.py --check   # exit 1 if the checked-in header is stale

The header is checked in so a bare clone builds (cpp/teleop's path_plan_check and
square_probe read it); `scripts/check motion-constants` runs --check so it cannot drift
from the JSON.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts/lib"))
from tatbot_paths import bootstrap  # noqa: E402

bootstrap()
import motion_constants as dc  # noqa: E402

HEADER = dc.ROOT / "cpp" / "teleop" / "motion_constants.hpp"


def _cpp(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        s = repr(value)
        return s if ("." in s or "e" in s) else s + ".0"
    raise TypeError(f"unsupported constant type {type(value).__name__}")


def render() -> str:
    lines = [
        "// GENERATED by scripts/gen_motion_constants.py from config/motion_constants.json.",
        "// Do not edit: change the JSON, rerun the generator, rebuild.",
        "#pragma once",
        "#include <array>",
        "",
        "namespace tatbot::motion_constants",
        "{",
        f'inline constexpr char SHA[] = "{dc.SHA}";',
        "",
    ]
    for key, value in dc.flat():
        name = key.upper().replace(".", "_")
        if isinstance(value, list):
            items = ", ".join(_cpp(v) for v in value)
            lines.append(f"inline constexpr std::array<double, {len(value)}> {name}{{{items}}};")
        else:
            ctype = "int" if isinstance(value, int) and not isinstance(value, bool) else "double"
            lines.append(f"inline constexpr {ctype} {name} = {_cpp(value)};")
    lines += ["", "}  // namespace tatbot::motion_constants", ""]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        current = HEADER.read_text() if HEADER.exists() else ""
        if current != text:
            print("motion constants header stale: run scripts/gen_motion_constants.py", file=sys.stderr)
            return 1
        print(f"motion constants {dc.SHA}: header current")
        return 0
    HEADER.write_text(text)
    print(f"wrote {HEADER.relative_to(dc.ROOT)} ({dc.SHA})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
