ip_address_l: "192.168.1.3"
ip_address_r: "192.168.1.2"
arm_l_config_filepath: "~/tatbot/config/trossen/arm_l.yaml"
arm_r_config_filepath: "~/tatbot/config/trossen/arm_r.yaml"
goal_time_fast: 0.06
goal_time_slow: 1.6
connection_timeout: 6.0
ee_rot_l:
  wxyz: [0.7071, 0.0, 0.0, -0.7071]
ee_rot_r:
  wxyz: [0.7071, 0.0, 0.0, 0.7071]
hover_offset:
  xyz: [0.0, 0.0, 0.001]
offset_range: [-0.001, 0.003]
offset_num: 5
ee_offset_l:
  xyz: [0.0, -0.001, -0.002]
ee_offset_r:
  xyz: [0.003, 0.016, 0.005]