ip_address_l: "192.168.1.3"
ip_address_r: "192.168.1.2"
arm_l_config_filepath: "~/tatbot/config/trossen/arm_l.yaml"
arm_r_config_filepath: "~/tatbot/config/trossen/arm_r.yaml"
goal_time_fast: 0.1
goal_time_slow: 2.0
connection_timeout: 10.0