description: "20mm x 10mm area used for testing"
image_width_m: 0.02
image_height_m: 0.01
image_width_px: 236
image_height_px: 118
design_pose:
  pos:
    xyz: [0.200, -0.012, 0.099]
  rot:
    wxyz: [0.781, -0.184, -0.207, 0.548]
zone_depth_m: 0.03
zone_width_m: 0.04
zone_height_m: 0.01
plymesh_dir: "~/tatbot/nfs/3d/default"