description: "20mm x 10mm area used for testing"
image_width_m: 0.02
image_height_m: 0.01
image_width_px: 236
image_height_px: 118
design_pose:
  pos:
    xyz: [0.22, 0.0, 0.08]
  rot:
    wxyz: [1.0, 0.0, 0.0, 0.0]
    # wxyz: [0.7071, 0.0, 0.0, -0.7071] # -90 degrees in Z
    # wxyz: [0.7071, 0.0, 0.0, 0.7071] # 90 degrees in Z
zone_depth_m: 0.03
zone_width_m: 0.04
zone_height_m: 0.01
plymesh_dir: "~/tatbot/nfs/3d/default"