description: "20mm x 10mm area used for testing"
image_width_m: 0.02
image_height_m: 0.01
image_width_px: 236
image_height_px: 118
design_pose:
  pos:
    xyz: [0.179, -0.002, 0.075]
  rot:
    wxyz: [0.854, -0.094, -0.094, 0.468]
zone_depth_m: 0.03
zone_width_m: 0.04
zone_height_m: 0.01
plymesh_dir: "~/tatbot/nfs/3d/default"