description: "92mm x 122mm x 40mm fake skin (5mm thickness)"
image_width_m: 0.1
image_height_m: 0.07
image_width_px: 1181
image_height_px: 826
design_pose:
  pos:
    xyz: [0.18, 0.0, -0.003]
  rot:
    # wxyz: [1.0, 0.0, 0.0, 0.0]
    wxyz: [0.7071, 0.0, 0.0, -0.7071] # -90 degrees in Z
    # wxyz: [0.7071, 0.0, 0.0, 0.7071] # 90 degrees in Z
zone_depth_m: 0.092
zone_width_m: 0.122
zone_height_m: 0.04