description: "50mm x 50mm square of fake skin"
image_width_m: 0.05
image_height_m: 0.05
image_width_px: 166
image_height_px: 166
design_pose:
  pos:
    xyz: [0.22, 0.0, 0.074]
  rot:
    # wxyz: [1.0, 0.0, 0.0, 0.0]
    wxyz: [0.7071, 0.0, 0.0, -0.7071] # -90 degrees in Z
    # wxyz: [0.7071, 0.0, 0.0, 0.7071] # 90 degrees in Z
zone_depth_m: 0.06
zone_width_m: 0.06
zone_height_m: 0.01
plymesh_dir: "~/tatbot/nfs/3d/default"