description: "small 5cm x 2cm patch of skin on hugo's right knee"
image_width_m: 0.05
image_height_m: 0.02
image_width_px: 1181
image_height_px: 826
design_pose:
  pos:
    xyz: [0.18, 0.0, -0.01]
  rot:
    wxyz: [0.7071, 0.0, 0.0, -0.7071] # -90 degrees in Z
zone_depth_m: 0.092
zone_width_m: 0.122
zone_height_m: 0.04
plymesh_dir: "~/tatbot/nfs/3d/knee"