description: "20mm x 10mm area on sponge fake skin"
image_width_m: 0.02
image_height_m: 0.01
design_pose:
  pos:
    xyz: [0.22, 0.0, 0.08]
  rot:
    wxyz: [0.7071, 0.0, 0.0, -0.7071]
zone_depth_m: 0.03
zone_width_m: 0.04
zone_height_m: 0.01
plymesh_dir: "~/tatbot/nfs/3d/default"
