# monitoring/inventory.yml – single source of truth for versions and topology

versions:
  # Server-side
  prometheus: "v3.5.0"
  grafana_oss: "12.1.1"

  # Exporters
  node_exporter: "1.9.1"
  dcgm_exporter: "4.4.0-4.5.0-ubi9"
  jetson_stats: "4.3.2"
  jetson_stats_exporter: "0.1.2"
  intel_gpu_exporter_image: "restreamio/intel-prometheus"
  intel_gpu_exporter_tag: "latest"  # consider pinning to a digest/tag
  rpi_exporter: "0.4.0"

scrape_interval: "15s"

nodes:
  eek:
    addr: "192.168.1.97:9100"
    roles: [node, server]
  ook:
    addr: "192.168.1.90:9100"
    roles: [node]
    gpu:
      nvidia_dcgm: { addr: "192.168.1.90:9400" }
  oop:
    addr: "192.168.1.51:9100"
    roles: [node]
    gpu:
      nvidia_dcgm: { addr: "192.168.1.51:9400" }
  hog:
    addr: "192.168.1.88:9100"
    roles: [node]
    gpu:
      intel: { addr: "192.168.1.88:8080" }
  ojo:
    # jetson-stats exporter includes CPU/mem + GPU on 9100; no separate node_exporter
    # Use the device's IP to avoid hostname issues
    jetson: { addr: "192.168.1.96:9100" }
  rpi1:
    addr: "192.168.1.98:9100"
    roles: [node, kiosk]
    rpi: { addr: "192.168.1.98:9110" }
  rpi2:
    addr: "192.168.1.99:9100"
    roles: [node]
    rpi: { addr: "192.168.1.99:9110" }
