cameras:
  camera1:
    ip: "192.168.1.91"
    username: "admin"  # Default Amcrest username
    password: "${CAMERA_1_PASSWORD}"  # Will be loaded from environment variable
    rtsp_port: 554
    stream_path: "/cam/realmonitor?channel=1&subtype=0"  # Main stream
    resolution: [2960, 1668]  # 5MP
    intrinsics:
      fov: 1.57  # example: 90 degrees in radians
      aspect: 1.77
      fx: 1000.0
      fy: 1000.0
      ppx: 1480.0
      ppy: 834.0
    extrinsics:
      pos:
        xyz: [0.0, 0.0, 0.0]
      rot:
        wxyz: [1.0, 0.0, 0.0, 0.0]
    fps: 5
  camera2:
    ip: "192.168.1.92"
    username: "admin"
    password: "${CAMERA_2_PASSWORD}"
    rtsp_port: 554
    stream_path: "/cam/realmonitor?channel=1&subtype=0"
    resolution: [2960, 1668]
    intrinsics:
      fov: 1.57
      aspect: 1.77
      fx: 1000.0
      fy: 1000.0
      ppx: 1480.0
      ppy: 834.0
    extrinsics:
      pos:
        xyz: [0.0, 0.0, 0.0]
      rot:
        wxyz: [1.0, 0.0, 0.0, 0.0]
    fps: 5
  camera3:
    ip: "192.168.1.93"
    username: "admin"
    password: "${CAMERA_3_PASSWORD}"
    rtsp_port: 554
    stream_path: "/cam/realmonitor?channel=1&subtype=0"
    resolution: [2960, 1668]
    intrinsics:
      fov: 1.57
      aspect: 1.77
      fx: 1000.0
      fy: 1000.0
      ppx: 1480.0
      ppy: 834.0
    extrinsics:
      pos:
        xyz: [0.0, 0.0, 0.0]
      rot:
        wxyz: [1.0, 0.0, 0.0, 0.0]
    fps: 5
  camera4:
    ip: "192.168.1.94"
    username: "admin"
    password: "${CAMERA_4_PASSWORD}"
    rtsp_port: 554
    stream_path: "/cam/realmonitor?channel=1&subtype=0"
    resolution: [2960, 1668]
    intrinsics:
      fov: 1.57
      aspect: 1.77
      fx: 1000.0
      fy: 1000.0
      ppx: 1480.0
      ppy: 834.0
    extrinsics:
      pos:
        xyz: [0.0, 0.0, 0.0]
      rot:
        wxyz: [1.0, 0.0, 0.0, 0.0]
    fps: 5
  camera5:
    ip: "192.168.1.95"
    username: "admin"
    password: "${CAMERA_5_PASSWORD}"
    rtsp_port: 554
    stream_path: "/cam/realmonitor?channel=1&subtype=0"
    resolution: [2960, 1668]
    intrinsics:
      fov: 1.57
      aspect: 1.77
      fx: 1000.0
      fy: 1000.0
      ppx: 1480.0
      ppy: 834.0
    extrinsics:
      pos:
        xyz: [0.0, 0.0, 0.0]
      rot:
        wxyz: [1.0, 0.0, 0.0, 0.0]
    fps: 5

output_dir: "output/cameras"  # Directory to save captured images
image_format: "jpg"  # Output image format