global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
- job_name: nodes
  static_configs:
  - targets:
    - 192.168.1.88:9100
    - eek:9100
    - ook:9100
    - rpi1:9100
    - rpi2:9100
- job_name: jetson
  static_configs:
  - targets:
    - ojo:9100
- job_name: nvidia_dgpu
  static_configs:
  - targets:
    - ook:9400
- job_name: intel_gpu
  static_configs:
  - targets:
    - 192.168.1.88:8080
- job_name: rpi_soc
  static_configs:
  - targets:
    - rpi1:9110
    - rpi2:9110
